"""
Seed script to populate the IR-IWQMS database with sample data.
Run from the backend/ directory:
    python seed.py
"""
import sys
import os

# Ensure the backend directory is on the path
sys.path.insert(0, os.path.dirname(__file__))

from database import SessionLocal, engine, Base
from models import user, hierarchy, master  # noqa: F401 â€” ensure all models registered
from models.user import User, UserRole
from models.hierarchy import Zone, Division, Station, WaterSource
from models.master import Parameter, WaterQualityStandard
from core.security import get_password_hash
from datetime import datetime, timedelta

# Create all tables
Base.metadata.create_all(bind=engine)

db = SessionLocal()

def seed_all():
    print("Seeding database...")

    # â”€â”€ Admin User â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    if not db.query(User).filter(User.employee_id == "ADMIN001").first():
        admin = User(
            employee_id="ADMIN001",
            name="Central Admin",
            email="admin@ir-iwqms.in",
            mobile_number="9000000001",
            hashed_password=get_password_hash("admin123"),
            role=UserRole.CENTRAL_ADMIN,
            is_active=True,
        )
        db.add(admin)
        db.commit()
        print("  âœ“ Admin user created (ADMIN001 / admin123)")
    else:
        print("  â€“ Admin user already exists")

    # â”€â”€ Zones â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    zone_data = [
        {"name": "Southern Railway", "code": "SR"},
    ]
    zones = {}
    for z in zone_data:
        existing = db.query(Zone).filter(Zone.code == z["code"]).first()
        if not existing:
            zone = Zone(**z)
            db.add(zone)
            db.commit()
            db.refresh(zone)
            zones[z["code"]] = zone
            print(f"  âœ“ Zone: {z['name']}")
        else:
            zones[z["code"]] = existing

    # â”€â”€ Divisions â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    division_data = [
        {"name": "Chennai Division", "code": "MAS", "zone_code": "SR"},
        {"name": "Trichy Division", "code": "TPJ", "zone_code": "SR"},
    ]
    divisions = {}
    for d in division_data:
        existing = db.query(Division).filter(Division.code == d["code"]).first()
        if not existing:
            div = Division(
                name=d["name"],
                code=d["code"],
                zone_id=zones[d["zone_code"]].id,
            )
            db.add(div)
            db.commit()
            db.refresh(div)
            divisions[d["code"]] = div
            print(f"  âœ“ Division: {d['name']}")
        else:
            divisions[d["code"]] = existing

    # â”€â”€ Stations â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    station_data = [
        {"name": "Chennai Central", "code": "MAS", "category": "NSG1", "div": "MAS", "lat": 10.3188, "lng": 76.1493},
        {"name": "Chennai egmore", "code": "MS", "category": "NSG 1", "div": "TPJ", "lat": 10.6812, "lng": 76.5806},
        {"name": "Tambaram", "code": "TBM", "category": "NSG1", "div": "MAS", "lat": 9.8521, "lng": 76.4791},
        {"name": "Arakkonam jn", "code": "AJJ", "category": "NSG 2", "div": "TPJ", "lat": 9.446, "lng": 78.165},
        {"name": "Avadi", "code": "AVD", "category": "NSG 2", "div": "MAS", "lat": 12.8434, "lng": 79.9607},
        {"name": "Chengalpattu jn.", "code": "CGL", "category": "NSG 2", "div": "TPJ", "lat": 9.1101, "lng": 78.3933},
        {"name": "Katpadi", "code": "KPD", "category": "NSG 2", "div": "MAS", "lat": 10.3034, "lng": 77.478},
        {"name": "Tiruvallur", "code": "TRL", "category": "NSG 2", "div": "TPJ", "lat": 11.359, "lng": 79.2837},
        {"name": "Coimbatore jn", "code": "CBE", "category": "NSG 2", "div": "MAS", "lat": 11.3546, "lng": 77.0719},
        {"name": "Kozhikkode", "code": "CLT", "category": "NSG 2", "div": "TPJ", "lat": 11.3921, "lng": 77.8557},
        {"name": "Ernakulam jn", "code": "ERS", "category": "NSG 2", "div": "MAS", "lat": 12.3733, "lng": 78.7206},
        {"name": "Thrissur", "code": "TCR", "category": "NSG 2", "div": "TPJ", "lat": 8.7514, "lng": 79.7197},
        {"name": "Tiruvananthapuram central", "code": "TVC", "category": "NSG 2", "div": "MAS", "lat": 10.6985, "lng": 77.8368},
        {"name": "Madurai jn", "code": "MDU", "category": "NSG2", "div": "TPJ", "lat": 9.5598, "lng": 76.6174},
        {"name": "Guduvancheri", "code": "Gl", "category": "NSG3", "div": "MAS", "lat": 12.6468, "lng": 79.7813},
        {"name": "Jolarpettai", "code": "JTJ", "category": "NSG3", "div": "TPJ", "lat": 11.9419, "lng": 79.5484},
        {"name": "Mambalam", "code": "MBM", "category": "NSG3", "div": "MAS", "lat": 8.2299, "lng": 76.0384},
        {"name": "Perambur", "code": "PER", "category": "NSG3", "div": "TPJ", "lat": 10.3351, "lng": 76.8879},
        {"name": "Perungalathur (FLAG", "code": "PRGL", "category": "NSG3", "div": "MAS", "lat": 10.1715, "lng": 77.1584},
        {"name": "Erode Jn", "code": "ED", "category": "NSG 3", "div": "TPJ", "lat": 9.4853, "lng": 78.0961},
        {"name": "Salem jn", "code": "SA", "category": "NSG 3", "div": "MAS", "lat": 11.8744, "lng": 77.1672},
        {"name": "Tiruppur", "code": "TUP", "category": "NSG3", "div": "TPJ", "lat": 9.4883, "lng": 79.993},
        {"name": "Kannur", "code": "CAN", "category": "NSG 3", "div": "MAS", "lat": 8.8081, "lng": 77.472},
        {"name": "Mangalore Central", "code": "MAQ", "category": "NSG3", "div": "TPJ", "lat": 10.4477, "lng": 76.1431},
        {"name": "Mangalore jn", "code": "MAJN", "category": "NSG3", "div": "MAS", "lat": 11.5478, "lng": 77.4861},
        {"name": "Palakkad jn.", "code": "PGT", "category": "NSG 3", "div": "TPJ", "lat": 12.7484, "lng": 76.164},
        {"name": "Shoranur jn.", "code": "SRR", "category": "NSG 3", "div": "MAS", "lat": 9.1854, "lng": 78.7135},
        {"name": "Thalassery", "code": "TLY", "category": "NSG3", "div": "TPJ", "lat": 10.2487, "lng": 76.557},
        {"name": "Tirur", "code": "TIR", "category": "NSG3", "div": "MAS", "lat": 12.7109, "lng": 77.2572},
        {"name": "Vadakara", "code": "BDJ", "category": "NSG 3", "div": "TPJ", "lat": 9.1534, "lng": 78.625},
        {"name": "Alappuzha", "code": "ALLP", "category": "NSG 3", "div": "MAS", "lat": 9.9494, "lng": 78.5224},
        {"name": "Aluva", "code": "AWY", "category": "NSG3", "div": "TPJ", "lat": 11.3722, "lng": 78.4648},
        {"name": "Chengannur", "code": "CNGR", "category": "NSG 3", "div": "MAS", "lat": 11.5651, "lng": 76.4451},
        {"name": "Ernakulam town", "code": "ERN", "category": "NSG3", "div": "TPJ", "lat": 11.8147, "lng": 79.49},
        {"name": "Kayankulam jn", "code": "KYJ", "category": "NSG 3", "div": "MAS", "lat": 8.7661, "lng": 78.1444},
        {"name": "Kochuveli", "code": "KCVL", "category": "NSG3", "div": "TPJ", "lat": 8.6828, "lng": 79.5587},
        {"name": "Kollam jn", "code": "QLN", "category": "NSG3", "div": "MAS", "lat": 10.9884, "lng": 76.3731},
        {"name": "Kottayam", "code": "KTYM", "category": "NSG3", "div": "TPJ", "lat": 10.8648, "lng": 77.5226},
        {"name": "Nagercoil jn", "code": "NCJ", "category": "NSG 3", "div": "MAS", "lat": 12.299, "lng": 77.555},
        {"name": "Thanjavur jn", "code": "TJ", "category": "NSG 3", "div": "TPJ", "lat": 8.9452, "lng": 77.5654},
        {"name": "Tiruchchirappalli jn", "code": "TPJ", "category": "NSG3", "div": "MAS", "lat": 12.9001, "lng": 76.762},
        {"name": "Villupuram jn.", "code": "VM", "category": "NSG3", "div": "TPJ", "lat": 11.7685, "lng": 76.4116},
        {"name": "Dindigul jn", "code": "DG", "category": "NSG 3", "div": "MAS", "lat": 10.5126, "lng": 78.4213},
        {"name": "Rameswaram", "code": "RMM", "category": "NSG 3", "div": "TPJ", "lat": 8.3349, "lng": 79.9995},
        {"name": "Tirunelveli jn", "code": "TEN", "category": "NSG3", "div": "MAS", "lat": 11.6675, "lng": 77.466},
        {"name": "Tuticorin", "code": "TN", "category": "NSG3", "div": "TPJ", "lat": 8.9261, "lng": 79.4263},
        {"name": "Kanchipuram", "code": "CJ", "category": "NSG4", "div": "MAS", "lat": 9.0068, "lng": 77.0382},
        {"name": "Melmaruvathur", "code": "MLMR", "category": "NSG 4", "div": "TPJ", "lat": 11.1868, "lng": 79.2816},
        {"name": "Singaperumalkoil", "code": "SKL", "category": "NSG 4", "div": "MAS", "lat": 12.4687, "lng": 79.4445},
        {"name": "Tiruttani", "code": "TRT", "category": "NSG 4", "div": "TPJ", "lat": 12.8304, "lng": 77.3726},
        {"name": "Coonoor", "code": "ONR", "category": "NSG 4", "div": "MAS", "lat": 11.509, "lng": 77.0733},
        {"name": "Karur jn.", "code": "KRR", "category": "NSG 4", "div": "TPJ", "lat": 12.0411, "lng": 79.6755},
        {"name": "Mettupalaiyam", "code": "MTP.", "category": "NSG 4", "div": "MAS", "lat": 12.48, "lng": 79.6402},
        {"name": "Udagamandalam", "code": "UAM", "category": "NSG4", "div": "TPJ", "lat": 12.4894, "lng": 78.2099},
        {"name": "Bekal Fort flag", "code": "BFR", "category": "NSG 4", "div": "MAS", "lat": 8.3127, "lng": 77.831},
        {"name": "Kanhangad", "code": "KZE", "category": "NSG 4", "div": "TPJ", "lat": 12.0477, "lng": 78.0843},
        {"name": "Kasargod", "code": "KGQ", "category": "NSG 4", "div": "MAS", "lat": 9.9206, "lng": 78.812},
        {"name": "Kuttipuram", "code": "KTU", "category": "NSG 4", "div": "TPJ", "lat": 9.6539, "lng": 77.7242},
        {"name": "Mahe", "code": "OTP", "category": "NSG 4", "div": "MAS", "lat": 10.9971, "lng": 78.4826},
        {"name": "Ottappalam", "code": "PAY", "category": "NSG 4", "div": "TPJ", "lat": 9.1387, "lng": 79.1024},
        {"name": "Payyannur", "code": "QLD", "category": "NSG3", "div": "MAS", "lat": 11.4308, "lng": 79.5917},
        {"name": "Quilandi", "code": "ULL", "category": "NSG 4", "div": "TPJ", "lat": 9.583, "lng": 79.0784},
        {"name": "Ullal", "code": "AFK", "category": "NSG 4", "div": "MAS", "lat": 11.1773, "lng": 78.4148},
        {"name": "", "code": "Angamali for kaladi", "category": "CGY", "div": "TPJ", "lat": 9.4872, "lng": 77.3399},
        {"name": "Changanacheri", "code": "GUV", "category": "NSG 4", "div": "MAS", "lat": 9.6874, "lng": 77.622},
        {"name": "Guruvayur", "code": "CAPE", "category": "NSG4", "div": "TPJ", "lat": 9.3017, "lng": 79.6046},
        {"name": "Kanniyakumari", "code": "TRVL", "category": "NSG 4", "div": "MAS", "lat": 9.5162, "lng": 77.45},
        {"name": "Tiruvalla", "code": "VAK", "category": "NSG 4", "div": "TPJ", "lat": 8.1012, "lng": 79.5921},
        {"name": "Varkalashivagiri", "code": "KMU", "category": "NSG 4", "div": "MAS", "lat": 9.8867, "lng": 76.9836},
        {"name": "Kumbakonam", "code": "MV", "category": "NSG 4", "div": "TPJ", "lat": 9.671, "lng": 78.7405},
        {"name": "Mayiladuthurai jn.", "code": "NGT", "category": "NSG4", "div": "MAS", "lat": 10.6628, "lng": 78.5195},
        {"name": "Nagappattinam", "code": "PDY", "category": "NSG 4", "div": "TPJ", "lat": 9.2709, "lng": 79.483},
        {"name": "Karaikkudi jn", "code": "KKDI", "category": "NSG 4", "div": "MAS", "lat": 11.8119, "lng": 77.8609},
        {"name": "Kovilpatti", "code": "CVP", "category": "NSG 4", "div": "TPJ", "lat": 11.4998, "lng": 79.051},
        {"name": "Palani", "code": "PLNI", "category": "NSG 4", "div": "MAS", "lat": 10.016, "lng": 78.254},
        {"name": "Ramanathapuram", "code": "RMD", "category": "NSG 4", "div": "TPJ", "lat": 10.0029, "lng": 77.9883},
        {"name": "Tenkasi jn", "code": "TSI", "category": "NSG 4", "div": "MAS", "lat": 11.2126, "lng": 78.4279},
        {"name": "Tiruchendur", "code": "TCN", "category": "NSG4", "div": "TPJ", "lat": 12.0076, "lng": 78.664},
        {"name": "Virudhunagar jn", "code": "VPT", "category": "NSG 4", "div": "MAS", "lat": 12.626, "lng": 78.8652},
        {"name": "Ambur", "code": "AB", "category": "NSG5", "div": "TPJ", "lat": 10.8354, "lng": 78.4683},
        {"name": "Ekambarakuppam (FLAG", "code": "EKM", "category": "NSG5", "div": "MAS", "lat": 8.0768, "lng": 78.9836},
        {"name": "Gudiyatham", "code": "GYM", "category": "NSG5", "div": "TPJ", "lat": 12.1284, "lng": 79.3713},
        {"name": "Kattangulathur", "code": "CIM", "category": "NSGS", "div": "MAS", "lat": 9.8846, "lng": 76.6922},
        {"name": "Nayudupeta", "code": "NYP", "category": "NSG5", "div": "TPJ", "lat": 8.8818, "lng": 79.1774},
        {"name": "Puttur", "code": "PUT", "category": "NSG5", "div": "MAS", "lat": 12.7263, "lng": 77.5256},
        {"name": "Sholinghur", "code": "SHU", "category": "NSG5S", "div": "TPJ", "lat": 9.3112, "lng": 78.2027},
        {"name": "Sullurupeta", "code": "SPE", "category": "NSGS", "div": "MAS", "lat": 9.523, "lng": 79.3115},
        {"name": "Tindivanam", "code": "TMV", "category": "NSG5", "div": "TPJ", "lat": 10.078, "lng": 77.7454},
        {"name": "Vandalur", "code": "VDR", "category": "NSG5", "div": "MAS", "lat": 12.2834, "lng": 78.0878},
        {"name": "\Vaniyambadi", "code": "VN", "category": "NSG5", "div": "TPJ", "lat": 12.1733, "lng": 79.0837},
        {"name": "Walajaroad", "code": "WJR", "category": "NSGS", "div": "MAS", "lat": 10.4703, "lng": 78.229},
        {"name": "Bommidi", "code": "Bal", "category": "NSG5", "div": "TPJ", "lat": 12.5148, "lng": 76.8299},
        {"name": "Chinna salem", "code": "CHSM", "category": "NSG5", "div": "MAS", "lat": 8.7227, "lng": 76.5579},
        {"name": "Kulitalai", "code": "KLT", "category": "NSG5S", "div": "TPJ", "lat": 9.2011, "lng": 79.8858},
        {"name": "Morappur", "code": "MAP.", "category": "NSGS", "div": "MAS", "lat": 8.5522, "lng": 79.1914},
        {"name": "Namakkal", "code": "NMKL", "category": "NSG5", "div": "TPJ", "lat": 11.7867, "lng": 78.5199},
        {"name": "Pugalur", "code": "PGR", "category": "NSGS", "div": "MAS", "lat": 8.3825, "lng": 79.1791},
        {"name": "Salem town", "code": "SXT", "category": "NSG5", "div": "TPJ", "lat": 12.2683, "lng": 78.6178},
        {"name": "Sankaridurg", "code": "SGE", "category": "NSG5", "div": "MAS", "lat": 11.688, "lng": 79.586},
        {"name": "Angadipuram", "code": "AAM", "category": "NSGS", "div": "TPJ", "lat": 11.793, "lng": 76.7942},
        {"name": "Charvattur", "code": "CHV", "category": "NSGS", "div": "MAS", "lat": 12.1867, "lng": 77.5032},
        {"name": "Ferok", "code": "FK", "category": "NSG5", "div": "TPJ", "lat": 9.7594, "lng": 78.7214},
        {"name": "Kannapuram", "code": "KPQ", "category": "NSG5", "div": "MAS", "lat": 8.638, "lng": 77.1613},
        {"name": "Kumbla", "code": "KMQ", "category": "NSG5", "div": "TPJ", "lat": 10.7975, "lng": 76.251},
        {"name": "Nilambur road", "code": "NIL", "category": "NSGS", "div": "MAS", "lat": 9.5317, "lng": 77.2215},
        {"name": "Nileshwar", "code": "NLE", "category": "NSG5", "div": "TPJ", "lat": 9.1914, "lng": 77.3186},
        {"name": "Palakkad town", "code": "PGTN", "category": "NSG5", "div": "MAS", "lat": 12.6865, "lng": 76.0089},
        {"name": "Parapanangadi", "code": "PGI", "category": "NSG5S", "div": "TPJ", "lat": 11.6061, "lng": 79.988},
        {"name": "Pattambi", "code": "PTB", "category": "NSG5S", "div": "MAS", "lat": 8.1614, "lng": 77.8487},
        {"name": "Payangadi", "code": "PAZ", "category": "NSG5", "div": "TPJ", "lat": 11.0192, "lng": 78.5131},
        {"name": "Pollachi", "code": "POY", "category": "NSG5", "div": "MAS", "lat": 11.0298, "lng": 77.9868},
        {"name": "Tanur", "code": "TA", "category": "NSG5", "div": "TPJ", "lat": 10.7562, "lng": 78.0163},
        {"name": "\Vaniyambalam", "code": "VNB", "category": "NSGS", "div": "MAS", "lat": 9.9402, "lng": 79.1956},
        {"name": "", "code": "Ambalapuzha", "category": "AMPA", "div": "TPJ", "lat": 11.2459, "lng": 77.3212},
        {"name": "Chalakudi", "code": "CKI", "category": "NSG5", "div": "MAS", "lat": 10.1756, "lng": 76.6875},
        {"name": "Cherthala", "code": "SRTL", "category": "NSG5", "div": "TPJ", "lat": 12.4635, "lng": 76.7038},
        {"name": "Chirayinkil (FLAG", "code": "CRY", "category": "NSG5S", "div": "MAS", "lat": 10.5559, "lng": 77.2379},
        {"name": "Eraniel", "code": "ERL", "category": "NSGS", "div": "TPJ", "lat": 12.4321, "lng": 76.8745},
        {"name": "Haripad", "code": "HAD", "category": "NSG5", "div": "MAS", "lat": 12.4951, "lng": 76.3398},
        {"name": "lrinjalakuda", "code": "WK", "category": "NSG5S", "div": "TPJ", "lat": 12.4884, "lng": 79.7508},
        {"name": "Karunagapalli", "code": "KPY", "category": "NSGS", "div": "MAS", "lat": 10.03, "lng": 76.247},
        {"name": "Kazhakuttom", "code": "KZK", "category": "NSG5", "div": "TPJ", "lat": 10.9622, "lng": 79.0627},
        {"name": "Kulitturai", "code": "KZT", "category": "NSG5", "div": "MAS", "lat": 11.4085, "lng": 78.3879},
        {"name": "Mavelikara", "code": "MVLK", "category": "NSG5", "div": "TPJ", "lat": 9.7337, "lng": 77.8487},
        {"name": "Nagercoil Town", "code": "NJT", "category": "NSGS", "div": "MAS", "lat": 12.8299, "lng": 77.6222},
        {"name": "Nanguneri", "code": "NNN", "category": "NSGS", "div": "TPJ", "lat": 11.5426, "lng": 77.348},
        {"name": "Neyyatinkara", "code": "NYY", "category": "NSG5", "div": "MAS", "lat": 11.498, "lng": 79.7732},
        {"name": "Parassala", "code": "PASA", "category": "NSG5", "div": "TPJ", "lat": 12.49, "lng": 78.9917},
        {"name": "Paravur", "code": "PVU", "category": "NSG5", "div": "MAS", "lat": 10.2791, "lng": 77.4321},
        {"name": "Piravam road", "code": "PVRD", "category": "NSGS", "div": "TPJ", "lat": 8.225, "lng": 77.1542},
        {"name": "Sasthankotta", "code": "STKT", "category": "NSG5", "div": "MAS", "lat": 9.046, "lng": 79.3629},
        {"name": "Tripunittura", "code": "TRTR", "category": "NSG5", "div": "TPJ", "lat": 8.4658, "lng": 76.2994},
        {"name": "Wadakancheri", "code": "WKI", "category": "NSGS", "div": "MAS", "lat": 12.2115, "lng": 76.8114},
        {"name": "", "code": "Ariyalur", "category": "ALU", "div": "TPJ", "lat": 12.3029, "lng": 78.0407},
        {"name": "Chidambaram", "code": "CDM", "category": "NSG5", "div": "MAS", "lat": 9.6387, "lng": 77.6627},
        {"name": "Cuddalore port jn.", "code": "CUPJ", "category": "NSG5", "div": "TPJ", "lat": 9.0777, "lng": 77.5354},
        {"name": "Karaikal", "code": "KIK", "category": "NSGS", "div": "MAS", "lat": 9.1207, "lng": 77.1017},
        {"name": "Lalgudi", "code": "LL", "category": "NSGS5", "div": "TPJ", "lat": 9.7024, "lng": 76.1462},
        {"name": "Mannargudi", "code": "MQ", "category": "NSG5", "div": "MAS", "lat": 9.9222, "lng": 77.7003},
        {"name": "Nagore", "code": "NCR", "category": "NSG5", "div": "TPJ", "lat": 8.5139, "lng": 78.6674},
        {"name": "Nidamangalam", "code": "NMJ", "category": "NSGS", "div": "MAS", "lat": 11.748, "lng": 76.7365},
        {"name": "Papanasam (FLAG", "code": "PML", "category": "NSGS", "div": "TPJ", "lat": 9.1271, "lng": 76.1552},
        {"name": "Sirkazhi", "code": "sY", "category": "NSG5", "div": "MAS", "lat": 8.4067, "lng": 79.2846},
        {"name": "Srirangam", "code": "SRGM", "category": "NSG5S", "div": "TPJ", "lat": 11.5358, "lng": 76.6423},
        {"name": "Tiruchchirappalli fort", "code": "TP", "category": "NSGS", "div": "MAS", "lat": 9.7883, "lng": 79.1994},
        {"name": "Tirukkovilur", "code": "TRK", "category": "NSG5", "div": "TPJ", "lat": 9.937, "lng": 78.8774},
        {"name": "Tiruppadirippuliyur", "code": "TDPR", "category": "NSG5", "div": "MAS", "lat": 10.2094, "lng": 79.7723},
        {"name": "Tiruvannamalai", "code": "T™NM", "category": "NSG5", "div": "TPJ", "lat": 12.6287, "lng": 76.6044},
        {"name": "Tiruvarur jn.", "code": "TVR", "category": "NSGS", "div": "MAS", "lat": 12.0047, "lng": 78.6332},
        {"name": "Tiruverumbur", "code": "TRB", "category": "NSGS", "div": "TPJ", "lat": 10.2659, "lng": 79.6143},
        {"name": "Velanganni", "code": "VLNK", "category": "NSG5", "div": "MAS", "lat": 10.2695, "lng": 77.3241},
        {"name": "Vellore cantonment", "code": "VLR", "category": "NSG5", "div": "TPJ", "lat": 10.0354, "lng": 76.5652},
        {"name": "Vriddhachalam jn.", "code": "vRi", "category": "NSG5", "div": "MAS", "lat": 12.6938, "lng": 79.4833},
        {"name": "", "code": "Ambasamudram", "category": "ASD", "div": "TPJ", "lat": 8.0469, "lng": 79.5979},
        {"name": "Devakottai road (FLAG", "code": "DKO.", "category": "NSG5", "div": "MAS", "lat": 8.7058, "lng": 79.031},
        {"name": "Kadayanallur", "code": "KDNL", "category": "NSG5", "div": "TPJ", "lat": 11.1191, "lng": 77.6186},
        {"name": "Kodaikkanal road", "code": "KQN", "category": "NSG5S", "div": "MAS", "lat": 11.8273, "lng": 78.1958},
        {"name": "Manamadurai jn", "code": "MNM", "category": "NSGS", "div": "TPJ", "lat": 10.1271, "lng": 76.3893},
        {"name": "Nazareth", "code": "NZT", "category": "NSG5", "div": "MAS", "lat": 10.7716, "lng": 76.363},
        {"name": "Oddanchatram", "code": "oDpc", "category": "NSG5", "div": "TPJ", "lat": 11.8773, "lng": 79.3426},
        {"name": "Paramakkudi", "code": "PMK", "category": "NSG5", "div": "MAS", "lat": 8.0858, "lng": 77.8033},
        {"name": "Pudukkotai", "code": "PDKT", "category": "NSGS", "div": "TPJ", "lat": 9.6579, "lng": 78.6799},
        {"name": "Rajapalayam", "code": "RJPM", "category": "NSGS", "div": "MAS", "lat": 8.7986, "lng": 76.1942},
        {"name": "Sankarankovil", "code": "SNKL", "category": "NSG5", "div": "TPJ", "lat": 11.2034, "lng": 77.8222},
        {"name": "Sattur", "code": "SRT", "category": "NSG5", "div": "MAS", "lat": 8.7573, "lng": 76.9113},
        {"name": "Sengottai", "code": "SCT", "category": "NSG5S", "div": "TPJ", "lat": 11.5328, "lng": 76.646},
        {"name": "Sholavandan", "code": "SDN", "category": "NSGS", "div": "MAS", "lat": 9.6649, "lng": 77.8437},
        {"name": "Sivaganga", "code": "SVGA", "category": "NSG5", "div": "TPJ", "lat": 8.8396, "lng": 78.3862},
        {"name": "Sivakasi", "code": "SVKS.", "category": "NSG5S", "div": "MAS", "lat": 9.9272, "lng": 76.055},
        {"name": "Srivilliputtur", "code": "SVPR", "category": "NSGS", "div": "TPJ", "lat": 8.0994, "lng": 79.2289},
        {"name": "Thirupparankundram", "code": "TDN", "category": "NSG5", "div": "MAS", "lat": 12.3249, "lng": 76.7899},
        {"name": "Tirumangalam", "code": "TMQ", "category": "NSG5", "div": "TPJ", "lat": 11.2262, "lng": 77.8466},
        {"name": "Tiruttangal (FLAG", "code": "TTL", "category": "NSG5", "div": "MAS", "lat": 11.8042, "lng": 79.5435},
        {"name": "'Vanchi maniyachi", "code": "MEJ", "category": "NSGS", "div": "TPJ", "lat": 10.7029, "lng": 78.8213},
        {"name": "Anna nagar", "code": "ANNG", "category": "NSG6", "div": "MAS", "lat": 10.4769, "lng": 76.4566},
        {"name": "Arambakkam", "code": "AKM", "category": "NSG6", "div": "TPJ", "lat": 8.1177, "lng": 77.656},
        {"name": "Chitteri", "code": "CTRE", "category": "NSG6", "div": "MAS", "lat": 12.292, "lng": 77.492},
        {"name": "Doravari chatram", "code": "DVR", "category": "NSG6", "div": "TPJ", "lat": 10.295, "lng": 78.7607},
        {"name": "Elavur", "code": "ELR", "category": "NSG6", "div": "MAS", "lat": 8.4762, "lng": 79.0921},
        {"name": "Karunguzhi", "code": "KGZ", "category": "NSG6", "div": "TPJ", "lat": 11.0661, "lng": 79.0448},
        {"name": "Kavanur", "code": "KVN", "category": "NSG6", "div": "MAS", "lat": 10.8917, "lng": 76.6871},
        {"name": "Kettandapatti", "code": "KDY", "category": "NSG6", "div": "TPJ", "lat": 10.0033, "lng": 77.1535},
        {"name": "Latteri", "code": "ul", "category": "NSG6", "div": "MAS", "lat": 10.4536, "lng": 77.8456},
        {"name": "Maduranthagam", "code": "MMK", "category": "NSG6", "div": "TPJ", "lat": 12.9212, "lng": 79.3463},
        {"name": "Mailam", "code": "MTL", "category": "NSG6", "div": "MAS", "lat": 12.4372, "lng": 77.9498},
        {"name": "Melpatti", "code": "MPI", "category": "NSG6", "div": "TPJ", "lat": 9.0834, "lng": 79.7149},
        {"name": "Mukundarayapuram", "code": "MCN", "category": "NSG6", "div": "MAS", "lat": 11.0802, "lng": 76.4193},
        {"name": "Mundiyambakkam", "code": "MYP.", "category": "NSG6", "div": "TPJ", "lat": 9.3442, "lng": 78.1333},
        {"name": "Nagari", "code": "NG", "category": "NSG6", "div": "MAS", "lat": 8.8502, "lng": 77.8771},
        {"name": "Odur", "code": "ODUR", "category": "NSG6", "div": "TPJ", "lat": 11.9261, "lng": 76.4695},
        {"name": "Olakur", "code": "OLA", "category": "NSG6", "div": "MAS", "lat": 9.5115, "lng": 78.2552},
        {"name": "Otivakkam", "code": "ov", "category": "NSG6", "div": "TPJ", "lat": 12.2388, "lng": 79.2219},
        {"name": "Pachakuppam", "code": "PCKM", "category": "NSG6", "div": "MAS", "lat": 11.3799, "lng": 76.8593},
        {"name": "Palur", "code": "PALR", "category": "NSG6", "div": "TPJ", "lat": 12.6449, "lng": 77.1765},
        {"name": "Pedapariya", "code": "PYA", "category": "NSG6", "div": "MAS", "lat": 10.9207, "lng": 79.7883},
        {"name": "Perani", "code": "PEI", "category": "NSG6", "div": "TPJ", "lat": 8.8908, "lng": 77.4118},
        {"name": "Polireddypalem", "code": "PEL", "category": "NSG6", "div": "MAS", "lat": 11.2077, "lng": 76.6823},
        {"name": "Ponpadi", "code": "Pol", "category": "NSG6", "div": "TPJ", "lat": 9.1265, "lng": 76.4165},
        {"name": "Pudi", "code": "PUDI", "category": "NSG6", "div": "MAS", "lat": 9.3214, "lng": 78.3516},
        {"name": "Sevur", "code": "SVUR", "category": "NSG6", "div": "TPJ", "lat": 12.3398, "lng": 77.6513},
        {"name": "Tada", "code": "TADA", "category": "NSG6", "div": "MAS", "lat": 9.2846, "lng": 79.6493},
        {"name": "Taduku", "code": "TDK", "category": "NSG6", "div": "TPJ", "lat": 8.7046, "lng": 78.893},
        {"name": "Thalangai", "code": "TUG", "category": "NSG6", "div": "MAS", "lat": 9.3386, "lng": 78.2928},
        {"name": "Thiruvalam", "code": "THL", "category": "NSG6", "div": "TPJ", "lat": 10.8334, "lng": 78.7538},
        {"name": "Tirumalpur", "code": "TMLP", "category": "NSG6", "div": "MAS", "lat": 12.3726, "lng": 76.5621},
        {"name": "Tozhupedu", "code": "TZD", "category": "NSG6", "div": "TPJ", "lat": 9.318, "lng": 76.1986},
        {"name": "\Valathoor", "code": "VLT", "category": "NSG6", "div": "MAS", "lat": 10.7587, "lng": 76.2704},
        {"name": "\Vepagunta", "code": "VGA", "category": "NSG6", "div": "TPJ", "lat": 10.2078, "lng": 76.2718},
        {"name": "Vikravandi", "code": "VVN", "category": "NSG6", "div": "MAS", "lat": 9.3961, "lng": 79.9085},
        {"name": "Vinnamangalam", "code": "VGM", "category": "NSG6", "div": "TPJ", "lat": 12.5845, "lng": 78.8909},
        {"name": "'Walajabad", "code": "WJ", "category": "NSG6", "div": "MAS", "lat": 12.9887, "lng": 79.8136},
        {"name": "Anangur", "code": "ANU", "category": "NSG6", "div": "TPJ", "lat": 12.7911, "lng": 76.6424},
        {"name": "Buddireddippatti", "code": "BDY", "category": "NSG6", "div": "MAS", "lat": 8.0193, "lng": 78.0221},
        {"name": "Cauvery", "code": "cv", "category": "NSG6", "div": "TPJ", "lat": 8.0005, "lng": 78.4745},
        {"name": "Chavadipalaiyam", "code": "cvD", "category": "NSG6", "div": "MAS", "lat": 12.0716, "lng": 79.4468},
        {"name": "Danishpet", "code": "DSPT", "category": "NSG6", "div": "TPJ", "lat": 10.5538, "lng": 79.0706},
        {"name": "Dasampatti", "code": "DST", "category": "NSG6", "div": "MAS", "lat": 11.8336, "lng": 76.9314},
        {"name": "Doddampatti", "code": "DPI", "category": "NSG6", "div": "TPJ", "lat": 11.3892, "lng": 77.458},
        {"name": "Elamanur", "code": "EL", "category": "NSG6", "div": "MAS", "lat": 10.0214, "lng": 76.8125},
        {"name": "Eriodu", "code": "EDU", "category": "NSG6", "div": "TPJ", "lat": 11.9356, "lng": 79.0871},
        {"name": "Ettapur road", "code": "ETP", "category": "NSG6", "div": "MAS", "lat": 11.6972, "lng": 79.7394},
        {"name": "Ingur", "code": "IGR", "category": "NSG6", "div": "TPJ", "lat": 12.7894, "lng": 76.9628},
        {"name": "Kagankarai", "code": "KEY", "category": "NSG6", "div": "MAS", "lat": 9.5341, "lng": 78.5678},
        {"name": "Kalangani", "code": "KLGN", "category": "NSG6", "div": "TPJ", "lat": 8.1356, "lng": 78.9351},
        {"name": "Karamadai", "code": "KAY", "category": "NSG6", "div": "MAS", "lat": 12.2528, "lng": 77.7326},
        {"name": "Karuppur", "code": "KPPR", "category": "NSG6", "div": "TPJ", "lat": 11.5154, "lng": 76.2453},
        {"name": "Ketti", "code": "KXT", "category": "NSG6", "div": "MAS", "lat": 12.6293, "lng": 78.3728},
        {"name": "Kodumudi", "code": "KMD.", "category": "NSG6", "div": "TPJ", "lat": 9.5644, "lng": 79.9807},
        {"name": "Lalapet", "code": "LP", "category": "NSG6", "div": "MAS", "lat": 10.853, "lng": 79.1135},
        {"name": "Lokur", "code": "LCR", "category": "NSG6", "div": "TPJ", "lat": 10.8964, "lng": 78.0696},
        {"name": "Lovedale", "code": "LOV", "category": "NSG6", "div": "MAS", "lat": 8.041, "lng": 79.9206},
        {"name": "Magudanchavadi", "code": "DC", "category": "NSG6", "div": "TPJ", "lat": 8.2486, "lng": 76.4706},
        {"name": "Mahadanapuram", "code": "MMH", "category": "NSG6", "div": "MAS", "lat": 9.6955, "lng": 79.6139},
        {"name": "Mallur", "code": "MALR", "category": "NSG6", "div": "TPJ", "lat": 12.626, "lng": 78.0194},
        {"name": "Mavelipalaiyam", "code": "MVPM", "category": "NSG6", "div": "MAS", "lat": 11.04, "lng": 77.9966},
        {"name": "Mayanur", "code": "MYU", "category": "NSG6", "div": "TPJ", "lat": 8.5983, "lng": 77.359},
        {"name": "Mecheri road", "code": "MCRD", "category": "NSG6", "div": "MAS", "lat": 8.9593, "lng": 76.2247},
        {"name": "Metturdam", "code": "MTDM", "category": "NSG6", "div": "TPJ", "lat": 8.9726, "lng": 79.5546},
        {"name": "Minnampalli", "code": "MPLI", "category": "NSG6", "div": "MAS", "lat": 11.8292, "lng": 77.8325},
        {"name": "Mohanur", "code": "MONR", "category": "NSG6", "div": "TPJ", "lat": 10.4018, "lng": 76.0739},
        {"name": "Mukhasa parur", "code": "MKSP-", "category": "NSG6", "div": "MAS", "lat": 8.8521, "lng": 77.7477},
        {"name": "Murthipalaiyam", "code": "MPLM", "category": "NSG6", "div": "TPJ", "lat": 12.3097, "lng": 76.0615},
        {"name": "Muttarasanallur", "code": "MTNL", "category": "NSG6", "div": "MAS", "lat": 12.7261, "lng": 78.9034},
        {"name": "Omalur", "code": "OML.", "category": "NSG6", "div": "TPJ", "lat": 11.6266, "lng": 77.7638},
        {"name": "Palaiyam", "code": "PALM", "category": "NSG6", "div": "MAS", "lat": 8.9533, "lng": 79.957},
        {"name": "Pasur", "code": "PAS", "category": "NSG6", "div": "TPJ", "lat": 9.7633, "lng": 79.8952},
        {"name": "Peddanayakkanpalaiyam (FLAG", "code": "PDKM", "category": "NSG6", "div": "MAS", "lat": 9.0396, "lng": 78.0779},
        {"name": "Perugamani", "code": "PGN", "category": "NSG6", "div": "TPJ", "lat": 11.6405, "lng": 76.2058},
        {"name": "Perundurai", "code": "PY", "category": "NSG6", "div": "MAS", "lat": 8.8654, "lng": 78.925},
        {"name": "Pettaivaytalai", "code": "PLI", "category": "NSG6", "div": "TPJ", "lat": 10.4672, "lng": 76.1965},
        {"name": "Pilamedu", "code": "PLMD", "category": "NSG6", "div": "MAS", "lat": 8.6107, "lng": 78.0745},
        {"name": "Pukkiravari", "code": "PRV", "category": "NSG6", "div": "TPJ", "lat": 11.881, "lng": 77.7031},
        {"name": "Rasipuram", "code": "RASP", "category": "NSG6", "div": "MAS", "lat": 10.6886, "lng": 77.4142},
        {"name": "Salem market", "code": "SAMT", "category": "NSG6", "div": "TPJ", "lat": 9.9407, "lng": 77.5256},
        {"name": "Sithalavai (FLAG", "code": "SEV", "category": "NSG6", "div": "MAS", "lat": 11.9151, "lng": 79.4347},
        {"name": "Somanur", "code": "SNO.", "category": "NSG6", "div": "TPJ", "lat": 12.6608, "lng": 77.5426},
        {"name": "Sulur road", "code": "SUU", "category": "NSG6", "div": "MAS", "lat": 8.0218, "lng": 76.4018},
        {"name": "Tinnappatti", "code": "TNT", "category": "NSG6", "div": "TPJ", "lat": 10.8936, "lng": 77.2166},
        {"name": "Totiyapalaiyam", "code": "TPM", "category": "NSG6", "div": "MAS", "lat": 10.2388, "lng": 79.2929},
        {"name": "Unjalur", "code": "URL", "category": "NSG6", "div": "TPJ", "lat": 9.1868, "lng": 77.2858},
        {"name": "Uttukuli", "code": "UKL", "category": "NSG6", "div": "MAS", "lat": 10.6637, "lng": 77.4068},
        {"name": "Vanjipalayam", "code": "VNJ", "category": "NSG6", "div": "TPJ", "lat": 8.2494, "lng": 78.5581},
        {"name": "\Veerarakiyam", "code": "VRQ", "category": "NSG6", "div": "MAS", "lat": 9.4027, "lng": 79.09},
        {"name": "Velliyanai", "code": "VEI", "category": "NSG6", "div": "TPJ", "lat": 10.8653, "lng": 77.4922},
        {"name": "Vijayamangalam", "code": "VZ", "category": "NSG6", "div": "MAS", "lat": 8.4796, "lng": 78.5561},
        {"name": "", "code": "Virapandy road", "category": "VRPD", "div": "TPJ", "lat": 10.1844, "lng": 77.6684},
        {"name": "Wellington", "code": "WEL", "category": "NSG6", "div": "MAS", "lat": 12.7484, "lng": 79.922},
        {"name": "Elattur", "code": "ETR", "category": "NSG6", "div": "TPJ", "lat": 8.7153, "lng": 77.2691},
        {"name": "Etakkot", "code": "ETK", "category": "NSG6", "div": "MAS", "lat": 8.9143, "lng": 77.7263},
        {"name": "Ettimadai", "code": "ETMD", "category": "NSG6", "div": "TPJ", "lat": 12.8161, "lng": 76.0687},
        {"name": "Jokatte", "code": "JOKT", "category": "NSG6", "div": "MAS", "lat": 10.0447, "lng": 76.9138},
        {"name": "Kadalundi", "code": "KN", "category": "NSG6", "div": "TPJ", "lat": 12.9837, "lng": 76.9597},
        {"name": "Kallayi", "code": "KUL", "category": "NSG6", "div": "MAS", "lat": 9.7934, "lng": 76.7957},
        {"name": "Kanjikode", "code": "KJKD.", "category": "NSG6", "div": "TPJ", "lat": 8.7169, "lng": 77.0435},
        {"name": "Kannur south", "code": "cs", "category": "NSG6", "div": "MAS", "lat": 12.1521, "lng": 79.6003},
        {"name": "Karakad", "code": "KRKD", "category": "NSG6", "div": "TPJ", "lat": 12.5266, "lng": 79.1901},
        {"name": "Kinattukkadavu", "code": "CNV", "category": "NSG6", "div": "MAS", "lat": 12.4615, "lng": 76.9434},
        {"name": "Kollengode", "code": "KLGD", "category": "NSG6", "div": "TPJ", "lat": 9.2574, "lng": 79.8737},
        {"name": "Kotikulam", "code": "KQK", "category": "NSG6", "div": "MAS", "lat": 8.0975, "lng": 76.9789},
        {"name": "Lakkiti", "code": "LDY", "category": "NSG6", "div": "TPJ", "lat": 10.1627, "lng": 78.3413},
        {"name": "Madukarai", "code": "MDKI", "category": "NSG6", "div": "MAS", "lat": 8.9385, "lng": 78.6286},
        {"name": "Manjeshwar", "code": "MJS.", "category": "NSG6", "div": "TPJ", "lat": 9.5994, "lng": 78.1792},
        {"name": "Mannanur", "code": "MNUR", "category": "NSG6", "div": "MAS", "lat": 12.5926, "lng": 79.3077},
        {"name": "Minatchipuram", "code": "MXM", "category": "NSG6", "div": "TPJ", "lat": 10.3559, "lng": 76.0385},
        {"name": "Muthalamada", "code": "MMDA", "category": "NSG6", "div": "MAS", "lat": 12.1699, "lng": 78.9373},
        {"name": "Pallipuram", "code": "PUM", "category": "NSG6", "div": "TPJ", "lat": 10.5964, "lng": 77.3384},
        {"name": "Parli", "code": "PLL", "category": "NSG6", "div": "MAS", "lat": 11.1533, "lng": 78.5699},
        {"name": "Payyoli (FLAG", "code": "PYOL", "category": "NSG6", "div": "TPJ", "lat": 12.8805, "lng": 76.6605},
        {"name": "Pudunagaram", "code": "PDGM", "category": "NSG6", "div": "MAS", "lat": 11.198, "lng": 76.7336},
        {"name": "Tikkotti", "code": "TKT", "category": "NSG6", "div": "TPJ", "lat": 8.8493, "lng": 79.4949},
        {"name": "Tirunnavaya", "code": "TUA", "category": "NSG6", "div": "MAS", "lat": 12.3314, "lng": 77.3995},
        {"name": "Trikarpur (FLAG", "code": "TKQ", "category": "NSG6", "div": "TPJ", "lat": 8.0149, "lng": 76.2884},
        {"name": "Uppala", "code": "UAA", "category": "NSG6", "div": "MAS", "lat": 10.1816, "lng": 79.1208},
        {"name": "Valapattanam", "code": "VAPM", "category": "NSG6", "div": "TPJ", "lat": 12.9414, "lng": 79.33},
        {"name": "Vallikunnu (FLAG", "code": "Vu", "category": "NSG6", "div": "MAS", "lat": 10.124, "lng": 79.3921},
        {"name": "Walayar", "code": "WRA", "category": "NSG6", "div": "TPJ", "lat": 10.3708, "lng": 78.7273},
        {"name": "West Hill", "code": "WH", "category": "NSG6", "div": "MAS", "lat": 11.5072, "lng": 77.6662},
        {"name": "", "code": "Aralvaymoli", "category": "AAY", "div": "TPJ", "lat": 8.1672, "lng": 79.8925},
        {"name": "Cheppad", "code": "CHPD", "category": "NSG6", "div": "MAS", "lat": 10.6643, "lng": 77.2876},
        {"name": "Chingavanam", "code": "CGV", "category": "NSG6", "div": "TPJ", "lat": 9.2383, "lng": 77.8047},
        {"name": "Edavai (FLAG", "code": "EVA", "category": "NSG6", "div": "MAS", "lat": 11.4379, "lng": 79.5304},
        {"name": "Ettumanur", "code": "ETM", "category": "NSG6", "div": "TPJ", "lat": 10.7185, "lng": 79.6159},
        {"name": "Idappalli", "code": "IPL.", "category": "NSG6", "div": "MAS", "lat": 8.6384, "lng": 77.3496},
        {"name": "Kadakavur", "code": "KVU", "category": "NSG6", "div": "TPJ", "lat": 10.7966, "lng": 79.9501},
        {"name": "Kalamasseri", "code": "KLMR", "category": "NSG6", "div": "MAS", "lat": 12.4716, "lng": 79.3586},
        {"name": "Kaniapuram (FLAG", "code": "KXP.", "category": "NSG6", "div": "TPJ", "lat": 12.8989, "lng": 77.011},
        {"name": "Karukutty", "code": "KUC.", "category": "NSG6", "div": "MAS", "lat": 11.9196, "lng": 79.16},
        {"name": "Kochi harbour terminus", "code": "CHTS", "category": "NSG6", "div": "TPJ", "lat": 10.2254, "lng": 76.5754},
        {"name": "Kumbalam", "code": "KUMM", "category": "NSG6", "div": "MAS", "lat": 8.0684, "lng": 79.3967},
        {"name": "Kuruppantara", "code": "KRPP-", "category": "NSG6", "div": "TPJ", "lat": 10.7921, "lng": 78.009},
        {"name": "Mararikulam", "code": "MAKM", "category": "NSG6", "div": "MAS", "lat": 8.4368, "lng": 77.5751},
        {"name": "Mayyanad", "code": "MYY", "category": "NSG6", "div": "TPJ", "lat": 10.8802, "lng": 78.6331},
        {"name": "Mulagunnathukavu", "code": "MGK", "category": "NSG6", "div": "MAS", "lat": 11.9794, "lng": 78.5205},
        {"name": "Mulanturutti", "code": "MNTT", "category": "NSG6", "div": "TPJ", "lat": 9.5619, "lng": 77.7664},
        {"name": "Murukkampuzha", "code": "MQU", "category": "NSG6", "div": "MAS", "lat": 12.5017, "lng": 79.3083},
        {"name": "Nemam", "code": "NEM", "category": "NSG6", "div": "TPJ", "lat": 11.3765, "lng": 78.7288},
        {"name": "North panakudi", "code": "NPK", "category": "NSG6", "div": "MAS", "lat": 12.5694, "lng": 76.9485},
        {"name": "Ochira", "code": "OCR", "category": "NSG6", "div": "TPJ", "lat": 10.2678, "lng": 79.3905},
        {"name": "Ollur", "code": "OLR", "category": "NSG6", "div": "MAS", "lat": 11.178, "lng": 77.4036},
        {"name": "Perinad", "code": "PRND", "category": "NSG6", "div": "TPJ", "lat": 12.2986, "lng": 79.3372},
        {"name": "Pudukad", "code": "PUK", "category": "NSG6", "div": "MAS", "lat": 9.9932, "lng": 79.5348},
        {"name": "Punkunnam", "code": "PNQ", "category": "NSG6", "div": "TPJ", "lat": 11.3139, "lng": 77.0461},
        {"name": "Sengulam", "code": "SGLM", "category": "NSG6", "div": "MAS", "lat": 12.9437, "lng": 78.6566},
        {"name": "Tiruvananthapuram pettah (FLAG", "code": "TVP", "category": "NSG6", "div": "TPJ", "lat": 12.3205, "lng": 78.5794},
        {"name": "Turavur", "code": "TUVR", "category": "NSG6", "div": "MAS", "lat": 9.535, "lng": 77.3166},
        {"name": "Vaikam road", "code": "VARD", "category": "NSG6", "div": "TPJ", "lat": 11.8002, "lng": 76.6114},
        {"name": "VallathoInagar", "code": "VTK", "category": "NSG6", "div": "MAS", "lat": 12.8408, "lng": 77.4272},
        {"name": "Adirampattinam", "code": "AMM", "category": "NSG6", "div": "TPJ", "lat": 12.2751, "lng": 79.1567},
        {"name": "Aduturai", "code": "ADT", "category": "NSG6", "div": "MAS", "lat": 8.2945, "lng": 79.0486},
        {"name": "", "code": "Agaram sibbandi", "category": "AGM", "div": "TPJ", "lat": 12.004, "lng": 78.3915},
        {"name": "Agastiampalli", "code": "AGX", "category": "NSG6", "div": "MAS", "lat": 9.6271, "lng": 77.9596},
        {"name": "", "code": "Alakkudi", "category": "ALK", "div": "TPJ", "lat": 9.8449, "lng": 77.9458},
        {"name": "", "code": "Alapakam", "category": "ALP", "div": "MAS", "lat": 11.1086, "lng": 76.5521},
        {"name": "", "code": "Anandatandavapuram", "category": "ANP.", "div": "TPJ", "lat": 10.3827, "lng": 76.9328},
        {"name": "", "code": "Arantangi", "category": "ATQ", "div": "MAS", "lat": 10.0145, "lng": 78.8132},
        {"name": "Arni road", "code": "ARV", "category": "NSG6", "div": "TPJ", "lat": 11.1506, "lng": 78.7264},
        {"name": "", "code": "Ayingudi", "category": "AY!", "div": "MAS", "lat": 8.1333, "lng": 78.6932},
        {"name": "Budalur", "code": "BAL", "category": "NSG6", "div": "TPJ", "lat": 10.8349, "lng": 77.8875},
        {"name": "Chinnababu samudram", "code": "CBU", "category": "NSG6", "div": "MAS", "lat": 11.9404, "lng": 79.0609},
        {"name": "Ichchangadu", "code": "ICG", "category": "NSG6", "div": "TPJ", "lat": 9.1015, "lng": 76.4667},
        {"name": "Kallagam", "code": "KLGM", "category": "NSG6", "div": "MAS", "lat": 9.1043, "lng": 77.3863},
        {"name": "Kallakkudi palanganatham", "code": "KKPM", "category": "NSG6", "div": "TPJ", "lat": 8.4201, "lng": 76.7579},
        {"name": "Kandambakkam", "code": "KDMD", "category": "NSG6", "div": "MAS", "lat": 8.2248, "lng": 79.7694},
        {"name": "Kaniyambadi", "code": "KNB", "category": "NSG6", "div": "TPJ", "lat": 11.4087, "lng": 78.5179},
        {"name": "Kannamangalam", "code": "KMM", "category": "NSG6", "div": "MAS", "lat": 8.3028, "lng": 76.9195},
        {"name": "Kille", "code": "Kil", "category": "NSG6", "div": "TPJ", "lat": 8.8372, "lng": 78.0526},
        {"name": "Kizhvelur", "code": "KVL.", "category": "NSG6", "div": "MAS", "lat": 10.4019, "lng": 78.4084},
        {"name": "Kollidam", "code": "CLN", "category": "NSG6", "div": "TPJ", "lat": 8.4978, "lng": 76.8625},
        {"name": "Koradacheri", "code": "KDE", "category": "NSG6", "div": "MAS", "lat": 11.9391, "lng": 77.8023},
        {"name": "Kulikarai", "code": "KU", "category": "NSG6", "div": "TPJ", "lat": 12.6531, "lng": 79.1145},
        {"name": "Kurinjipadi", "code": "KJPD", "category": "NSG6", "div": "MAS", "lat": 12.1727, "lng": 78.9482},
        {"name": "Kutralam", "code": "KTM", "category": "NSG6", "div": "TPJ", "lat": 8.5343, "lng": 77.0129},
        {"name": "Mambalapattu", "code": "MMP", "category": "NSG6", "div": "MAS", "lat": 8.7911, "lng": 77.1142},
        {"name": "Mathur", "code": "MTUR", "category": "NSG6", "div": "TPJ", "lat": 11.7388, "lng": 76.044},
        {"name": "Melpattambakkam", "code": "MBU", "category": "NSG6", "div": "MAS", "lat": 10.2736, "lng": 76.83},
        {"name": "Nannilam", "code": "NNM", "category": "NSG6", "div": "TPJ", "lat": 11.9465, "lng": 78.024},
        {"name": "Nellikuppam", "code": "NPM", "category": "NSG6", "div": "MAS", "lat": 12.9021, "lng": 76.5553},
        {"name": "Neyveli", "code": "NVL.", "category": "NSG6", "div": "TPJ", "lat": 8.7598, "lng": 79.4169},
        {"name": "Ottakovil", "code": "OTK", "category": "NSG6", "div": "MAS", "lat": 11.0879, "lng": 79.6777},
        {"name": "Pandaravadai", "code": "PDV", "category": "NSG6", "div": "TPJ", "lat": 11.9946, "lng": 79.6658},
        {"name": "Panruti", "code": "PRT", "category": "NSG6", "div": "MAS", "lat": 11.9795, "lng": 78.3499},
        {"name": "Parikkal", "code": "PRKL", "category": "NSG6", "div": "TPJ", "lat": 9.7288, "lng": 77.9661},
        {"name": "Pattukottai", "code": "PKT", "category": "NSG6", "div": "MAS", "lat": 11.1593, "lng": 77.3304},
        {"name": "Pennadam (FLAG", "code": "PNDM", "category": "NSG6", "div": "TPJ", "lat": 12.1866, "lng": 79.4136},
        {"name": "Peralam .", "code": "PEM", "category": "NSG6", "div": "MAS", "lat": 10.0519, "lng": 79.1096},
        {"name": "Peravuruni", "code": "PVI", "category": "NSG6", "div": "TPJ", "lat": 12.7734, "lng": 78.6642},
        {"name": "Periyakottai", "code": "PYK", "category": "NSG6", "div": "MAS", "lat": 10.3942, "lng": 79.9515},
        {"name": "Polur", "code": "PRL", "category": "NSG6", "div": "TPJ", "lat": 8.4382, "lng": 77.6351},
        {"name": "Ponmalai (golden rock", "code": "GOC", "category": "NSG6", "div": "MAS", "lat": 11.7519, "lng": 77.8613},
        {"name": "Puduchattiram", "code": "PUC", "category": "NSG6", "div": "TPJ", "lat": 9.9783, "lng": 79.2882},
        {"name": "Pullambadi", "code": "PMB", "category": "NSG6", "div": "MAS", "lat": 11.6588, "lng": 79.8988},
        {"name": "Puvanur", "code": "PVN", "category": "NSG6", "div": "TPJ", "lat": 9.1591, "lng": 79.7369},
        {"name": "Saliyamangalam", "code": "SMM", "category": "NSG6", "div": "MAS", "lat": 12.0108, "lng": 77.798},
        {"name": "Sendurai", "code": "SNDI", "category": "NSG6", "div": "TPJ", "lat": 10.6393, "lng": 76.9334},
        {"name": "Serndanur", "code": "SXR", "category": "NSG6", "div": "MAS", "lat": 11.3675, "lng": 78.19},
        {"name": "Sillakkudi", "code": "SLTH", "category": "NSG6", "div": "TPJ", "lat": 10.2965, "lng": 77.0072},
        {"name": "Solagampatti", "code": "SGM", "category": "NSG6", "div": "MAS", "lat": 9.1333, "lng": 79.0948},
        {"name": "Sundaraperumal Koil", "code": "SPL", "category": "NSG6", "div": "TPJ", "lat": 10.0843, "lng": 76.0758},
        {"name": "Talanallur", "code": "TLNR", "category": "NSG6", "div": "MAS", "lat": 9.1574, "lng": 76.3718},
        {"name": "Tandarai", "code": "TNI", "category": "NSG6", "div": "TPJ", "lat": 10.6448, "lng": 79.055},
        {"name": "Thiruthuraiyur", "code": "TUY", "category": "NSG6", "div": "MAS", "lat": 10.9673, "lng": 76.4551},
        {"name": "Tillaivilagam", "code": "TAM", "category": "NSG6", "div": "TPJ", "lat": 10.7701, "lng": 77.0436},
        {"name": "Tiruchchirappalli town", "code": "TPTN", "category": "NSG6", "div": "MAS", "lat": 12.4624, "lng": 78.5989},
        {"name": "Tirunelikaval", "code": "TNK", "category": "NSG6", "div": "TPJ", "lat": 9.0016, "lng": 78.2618},
        {"name": "Tiruturaipundi jn.", "code": "TTP", "category": "NSG6", "div": "MAS", "lat": 12.6986, "lng": 78.7496},
        {"name": "Tiruvennainallur road", "code": "TVNL", "category": "NSG6", "div": "TPJ", "lat": 9.9568, "lng": 76.2808},
        {"name": "Titte", "code": "T", "category": "NSG6", "div": "MAS", "lat": 12.4217, "lng": 79.7685},
        {"name": "Turinjapuram", "code": "TJM", "category": "NSG6", "div": "TPJ", "lat": 9.131, "lng": 77.0098},
        {"name": "Ulundurpet", "code": "ULU", "category": "NSG6", "div": "MAS", "lat": 12.703, "lng": 76.9036},
        {"name": "Uttangal mangalam", "code": "UMG", "category": "NSG6", "div": "TPJ", "lat": 10.0643, "lng": 79.708},
        {"name": "Vadalur", "code": "VLU", "category": "NSG6", "div": "MAS", "lat": 10.1839, "lng": 78.5235},
        {"name": "Vaithisvarankoil", "code": "VDL.", "category": "NSG6", "div": "TPJ", "lat": 10.8304, "lng": 79.8242},
        {"name": "Valadi", "code": "VLDE", "category": "NSG6", "div": "MAS", "lat": 12.8025, "lng": 76.7401},
        {"name": "\Venkatesapuram", "code": "VKM", "category": "NSG6", "div": "TPJ", "lat": 10.0976, "lng": 77.1065},
        {"name": "", "code": "Akkaraippatti", "category": "API", "div": "MAS", "lat": 11.6461, "lng": 77.5541},
        {"name": "Alwar tirunagari (FLAG", "code": "AWT", "category": "NSG6", "div": "TPJ", "lat": 9.39, "lng": 77.7187},
        {"name": "", "code": "Ambaturai", "category": "ABI", "div": "MAS", "lat": 8.6019, "lng": 76.5495},
        {"name": "Andipatti", "code": "ADPT", "category": "NSG6", "div": "TPJ", "lat": 10.4397, "lng": 76.1662},
        {"name": "", "code": "Arumuganeri", "category": "ANY", "div": "MAS", "lat": 9.5977, "lng": 78.786},
        {"name": "", "code": "Aruppukkottai", "category": "APK", "div": "TPJ", "lat": 8.538, "lng": 77.5171},
        {"name": "Auvaneeswarem", "code": "AVS", "category": "NSG6", "div": "MAS", "lat": 8.707, "lng": 76.8985},
        {"name": "", "code": "Ayyalur", "category": "AYR", "div": "TPJ", "lat": 9.4141, "lng": 77.0498},
        {"name": "Bhagavathipuram", "code": "BJM", "category": "NSG6", "div": "MAS", "lat": 9.0475, "lng": 77.125},
        {"name": "Bodinayakkanur", "code": "BDNK", "category": "NSG6", "div": "TPJ", "lat": 12.6644, "lng": 76.262},
        {"name": "Chatrappatti", "code": "CHPT", "category": "NSG6", "div": "MAS", "lat": 9.9771, "lng": 76.0602},
        {"name": "Cheran mahadevi", "code": "SMD.", "category": "NSG6", "div": "TPJ", "lat": 12.2382, "lng": 79.4483},
        {"name": "Chettinad", "code": "CTND", "category": "NSG6", "div": "MAS", "lat": 12.9326, "lng": 78.0898},
        {"name": "Edamann", "code": "EDN", "category": "NSG6", "div": "TPJ", "lat": 9.7379, "lng": 76.1866},
        {"name": "Ezhukone (FLAG", "code": "EKN", "category": "NSG6", "div": "MAS", "lat": 10.6443, "lng": 78.0446},
        {"name": "Gangaikondan", "code": "GDN", "category": "NSG6", "div": "TPJ", "lat": 12.926, "lng": 76.0061},
        {"name": "Gomangalam", "code": "GMGM", "category": "NSG6", "div": "MAS", "lat": 8.1844, "lng": 78.6388},
        {"name": "Kachchanavilai (FLAG", "code": "KCHV", "category": "NSG6", "div": "TPJ", "lat": 11.0502, "lng": 78.2038},
        {"name": "Kadambur", "code": "KDU", "category": "NSG6", "div": "MAS", "lat": 12.2152, "lng": 78.6922},
        {"name": "Kallal", "code": "KAL", "category": "NSG6", "div": "TPJ", "lat": 10.9964, "lng": 77.8928},
        {"name": "Kallidaikurichi (FLAG", "code": "KIC.", "category": "NSG6", "div": "MAS", "lat": 8.9231, "lng": 79.2922},
        {"name": "Kalligudi", "code": "KGD", "category": "NSG6", "div": "TPJ", "lat": 11.3613, "lng": 76.9934},
        {"name": "Kalpattichatram", "code": "KFC", "category": "NSG6", "div": "MAS", "lat": 12.4374, "lng": 77.0922},
        {"name": "Kayalpattinam (FLAG", "code": "KZY", "category": "NSG6", "div": "TPJ", "lat": 8.7342, "lng": 78.3129},
        {"name": "Keeranur", "code": "KRUR", "category": "NSG6", "div": "MAS", "lat": 9.4553, "lng": 77.9169},
        {"name": "Kilakadaiyam", "code": "KKY", "category": "NSG6", "div": "TPJ", "lat": 8.0305, "lng": 79.2078},
        {"name": "Kilikollur", "code": "KLQ", "category": "NSG6", "div": "MAS", "lat": 10.1681, "lng": 78.1252},
        {"name": "Kizhapuliyur (FLAG", "code": "KYZ", "category": "NSG6", "div": "TPJ", "lat": 9.9078, "lng": 78.5257},
        {"name": "Kolathur", "code": "KLS", "category": "NSG6", "div": "MAS", "lat": 12.5027, "lng": 79.9685},
        {"name": "Kottarakara", "code": "KKZ", "category": "NSG6", "div": "TPJ", "lat": 10.4099, "lng": 77.5509},
        {"name": "Kudalnagar", "code": "KON", "category": "NSG6", "div": "MAS", "lat": 8.4639, "lng": 78.499},
        {"name": "Kumaramangalam", "code": "KRMG", "category": "NSG6", "div": "TPJ", "lat": 9.9648, "lng": 76.0599},
        {"name": "Kundara", "code": "KUV", "category": "NSG6", "div": "MAS", "lat": 11.871, "lng": 79.2672},
        {"name": "Kurumbur (FLAG", "code": "KZB", "category": "NSG6", "div": "TPJ", "lat": 9.7756, "lng": 76.7924},
        {"name": "Madurai east (FLAG", "code": "MES", "category": "NSG6", "div": "MAS", "lat": 9.044, "lng": 78.3883},
        {"name": "Maivadi road", "code": "MVRD.", "category": "NSG6", "div": "TPJ", "lat": 12.2993, "lng": 77.5681},
        {"name": "Manaparai", "code": "MPA", "category": "NSG6", "div": "MAS", "lat": 8.0911, "lng": 77.8052},
        {"name": "Mandapam", "code": "MMM", "category": "NSG6", "div": "TPJ", "lat": 10.8555, "lng": 77.3602},
        {"name": "Melakkonnakkulam", "code": "MEKM", "category": "NSG6", "div": "MAS", "lat": 9.8285, "lng": 77.203},
        {"name": "Mettur (FLAG", "code": "MTE", "category": "NSG6", "div": "TPJ", "lat": 8.167, "lng": 76.029},
        {"name": "Milavittan", "code": "MVN", "category": "NSG6", "div": "MAS", "lat": 12.7579, "lng": 77.3756},
        {"name": "Narikkudi", "code": "NKK", "category": "NSG6", "div": "TPJ", "lat": 11.5817, "lng": 79.1647},
        {"name": "New Aryankavu", "code": "AYVN", "category": "NSG6", "div": "MAS", "lat": 9.7123, "lng": 77.9088},
        {"name": "Palayamkottai (FLAG", "code": "PCO", "category": "NSG6", "div": "TPJ", "lat": 10.9343, "lng": 76.5835},
        {"name": "Pambakovil shandy", "code": "PBKS", "category": "NSG6", "div": "MAS", "lat": 9.2635, "lng": 78.8886},
        {"name": "Pamban", "code": "PBM", "category": "NSG6", "div": "TPJ", "lat": 12.3918, "lng": 79.914},
        {"name": "Panangudi", "code": "PNGI", "category": "NSG6", "div": "MAS", "lat": 9.8227, "lng": 78.9557},
        {"name": "Pavurchatram", "code": "PCM", "category": "NSG6", "div": "TPJ", "lat": 10.8655, "lng": 79.649},
        {"name": "Pettai (FLAG", "code": "PEA", "category": "NSG6", "div": "MAS", "lat": 9.4991, "lng": 78.1228},
        {"name": "Punalur", "code": "PUU", "category": "NSG6", "div": "TPJ", "lat": 12.829, "lng": 79.6891},
        {"name": "Punggudi", "code": "PUG", "category": "NSG6", "div": "MAS", "lat": 12.9731, "lng": 77.449},
        {"name": "Pushpattur", "code": "PPTR", "category": "NSG6", "div": "TPJ", "lat": 10.486, "lng": 76.7811},
        {"name": "Ravanasamudram (FLAG", "code": "RVS", "category": "NSG6", "div": "MAS", "lat": 10.6677, "lng": 77.7052},
        {"name": "Samayanallur", "code": "SER", "category": "NSG6", "div": "TPJ", "lat": 9.0643, "lng": 78.2266},
        {"name": "Sattirakkudi", "code": "saQD", "category": "NSG6", "div": "MAS", "lat": 11.3712, "lng": 78.2523},
        {"name": "Seydunganallur", "code": "SDNR", "category": "NSG6", "div": "TPJ", "lat": 12.0471, "lng": 77.5751},
        {"name": "Silaiman", "code": "ILA", "category": "NSG6", "div": "MAS", "lat": 8.7221, "lng": 79.4778},
        {"name": "Srivaikuntam", "code": "SVV", "category": "NSG6", "div": "TPJ", "lat": 11.9909, "lng": 78.2569},
        {"name": "Sudiyur", "code": "SUX", "category": "NSG6", "div": "MAS", "lat": 12.3733, "lng": 79.4783},
        {"name": "Talaiyuthu", "code": "TAY", "category": "NSG6", "div": "TPJ", "lat": 11.9174, "lng": 76.0734},
        {"name": "Tamaraipadi", "code": "TMP.", "category": "NSG6", "div": "MAS", "lat": 12.2148, "lng": 77.5464},
        {"name": "Tattaparai", "code": "TIP", "category": "NSG6", "div": "TPJ", "lat": 9.5241, "lng": 79.1709},
        {"name": "Teni", "code": "TENI", "category": "NSG6", "div": "MAS", "lat": 11.677, "lng": 76.8288},
        {"name": "Tenmalai", "code": "TML", "category": "NSG6", "div": "TPJ", "lat": 9.9576, "lng": 77.0144},
        {"name": "Thathankulam (FLAG", "code": "TTQ", "category": "NSG6", "div": "MAS", "lat": 12.9374, "lng": 77.0053},
        {"name": "Tiruchchuli", "code": "TCH", "category": "NSG6", "div": "TPJ", "lat": 9.7426, "lng": 77.1874},
        {"name": "Tirumayam", "code": "TYM", "category": "NSG6", "div": "MAS", "lat": 10.6475, "lng": 78.0033},
        {"name": "Tirunelveli town", "code": "TYT", "category": "NSG6", "div": "TPJ", "lat": 11.1299, "lng": 79.742},
        {"name": "Tiruppachetti", "code": "TPC", "category": "NSG6", "div": "MAS", "lat": 12.1473, "lng": 76.6331},
        {"name": "Tiruppuvanam", "code": "TVN", "category": "NSG6", "div": "TPJ", "lat": 12.3309, "lng": 76.9457},
        {"name": "Tulukapatti", "code": "TY", "category": "NSG6", "div": "MAS", "lat": 11.5516, "lng": 79.7858},
        {"name": "Uchippuli", "code": "ucP.", "category": "NSG6", "div": "TPJ", "lat": 9.0679, "lng": 78.8288},
        {"name": "Udumalaippettai", "code": "UDT", "category": "NSG6", "div": "MAS", "lat": 8.7618, "lng": 78.7093},
        {"name": "Usilampatti", "code": "USLP", "category": "NSG6", "div": "TPJ", "lat": 10.2201, "lng": 78.2379},
        {"name": "Vadamadurai", "code": "VDM", "category": "NSG6", "div": "MAS", "lat": 8.2062, "lng": 77.8543},
        {"name": "Vadipatti", "code": "VDP", "category": "NSG6", "div": "TPJ", "lat": 11.1192, "lng": 77.7359},
        {"name": "Vaiyampatti", "code": "VPJ", "category": "NSG6", "div": "MAS", "lat": 11.0193, "lng": 76.7976},
        {"name": "Vellanur", "code": "VEL", "category": "NSG6", "div": "TPJ", "lat": 10.1562, "lng": 76.8164},
        {"name": "Chennai Beach", "code": "MSB", "category": "SG1", "div": "MAS", "lat": 9.0078, "lng": 76.3722},
        {"name": "Guindy", "code": "GDY", "category": "SG2", "div": "TPJ", "lat": 9.4971, "lng": 77.3204},
        {"name": "Pazhavanthangal (FLAG", "code": "PZA", "category": "SG2", "div": "MAS", "lat": 12.3596, "lng": 77.3346},
        {"name": "Velacheri", "code": "VLCY", "category": "SG2", "div": "TPJ", "lat": 11.2391, "lng": 77.5233},
        {"name": "Ambattur", "code": "ABU", "category": "SG3", "div": "MAS", "lat": 8.6734, "lng": 77.0629},
        {"name": "Annanur (HALT", "code": "ANNR", "category": "SG3", "div": "TPJ", "lat": 11.9053, "lng": 78.3627},
        {"name": "Anuppampattu (FLAG", "code": "APB", "category": "SG3", "div": "MAS", "lat": 9.5606, "lng": 79.0362},
        {"name": "Atthipattu (FLAG", "code": "AIP.", "category": "SG3", "div": "TPJ", "lat": 9.4069, "lng": 77.7158},
        {"name": "", "code": "Attipattupudunagar (HALT)", "category": "AIPP", "div": "MAS", "lat": 8.3653, "lng": 77.2281},
        {"name": "Basin bridge jn", "code": "BBQ", "category": "SG3", "div": "TPJ", "lat": 11.7597, "lng": 77.405},
        {"name": "Chennai Chetpet (FLAG", "code": "MSC.", "category": "SG3", "div": "MAS", "lat": 9.6, "lng": 79.9883},
        {"name": "Chennai fort (FLAG", "code": "MSF", "category": "SG3", "div": "TPJ", "lat": 12.0028, "lng": 76.9994},
        {"name": "Chennai park", "code": "MPK", "category": "SG3", "div": "MAS", "lat": 11.1397, "lng": 78.501},
        {"name": "Chepauk", "code": "MCPK", "category": "SG3", "div": "TPJ", "lat": 8.3495, "lng": 77.8772},
        {"name": "Chintadripet", "code": "MCPT", "category": "SG3", "div": "MAS", "lat": 9.0322, "lng": 79.1788},
        {"name": "Chrompet (FLAG", "code": "CMP", "category": "SG3", "div": "TPJ", "lat": 8.031, "lng": 79.3912},
        {"name": "Egattur (HALT", "code": "EGT", "category": "SG3", "div": "MAS", "lat": 9.9184, "lng": 77.9022},
        {"name": "Ennore", "code": "ENR", "category": "SG3", "div": "TPJ", "lat": 12.2915, "lng": 77.554},
        {"name": "Greenways road (FLAG", "code": "GWYR", "category": "SG3", "div": "MAS", "lat": 8.0263, "lng": 77.5256},
        {"name": "Gummidipundi", "code": "GPD", "category": "SG3", "div": "TPJ", "lat": 12.1697, "lng": 77.4769},
        {"name": "Hindu college (HALT", "code": "HC", "category": "SG3", "div": "MAS", "lat": 11.4399, "lng": 76.17},
        {"name": "Indiranagar (FLAG", "code": "INDR", "category": "SG3", "div": "TPJ", "lat": 9.941, "lng": 77.8514},
        {"name": "Kadambattur", "code": "KBT", "category": "SG3", "div": "MAS", "lat": 10.096, "lng": 76.0797},
        {"name": "Kasturibanagar (FLAG", "code": "KTBR", "category": "SG3", "div": "TPJ", "lat": 8.553, "lng": 77.0999},
        {"name": "Kathivakkam (FLAG", "code": "KAVM", "category": "SG3", "div": "MAS", "lat": 12.5547, "lng": 76.8613},
        {"name": "Kavaraipettai", "code": "KVP.", "category": "SG3", "div": "TPJ", "lat": 8.818, "lng": 79.9673},
        {"name": "Kodambakkam", "code": "MKK", "category": "SG3", "div": "MAS", "lat": 11.7343, "lng": 76.6684},
        {"name": "Korattur (FLAG", "code": "KOTR", "category": "SG3", "div": "TPJ", "lat": 12.6559, "lng": 77.0443},
        {"name": "Korukkupet", "code": "KOK", "category": "SG3", "div": "MAS", "lat": 11.3355, "lng": 77.9205},
        {"name": "Kotturpuram (FLAG", "code": "KTPM", "category": "SG3", "div": "TPJ", "lat": 9.7148, "lng": 79.0394},
        {"name": "Light house (FLAG", "code": "MLHS.", "category": "SG3", "div": "MAS", "lat": 11.8331, "lng": 78.323},
        {"name": "Manavur (FLAG", "code": "MAF", "category": "SG3", "div": "TPJ", "lat": 10.2279, "lng": 78.8411},
        {"name": "Mandaiveli (FLAG", "code": "MNDY", "category": "SG3", "div": "MAS", "lat": 8.835, "lng": 77.3687},
        {"name": "Meenambakkam", "code": "MN", "category": "SG3", "div": "TPJ", "lat": 12.3361, "lng": 79.0223},
        {"name": "Minjur", "code": "MJR", "category": "SG3", "div": "MAS", "lat": 11.0176, "lng": 78.4531},
        {"name": "Moore Market Complex", "code": "MASS.", "category": "SG3", "div": "TPJ", "lat": 10.3661, "lng": 77.8504},
        {"name": "Mosur (HALT", "code": "MSU", "category": "SG3", "div": "MAS", "lat": 10.4971, "lng": 77.1766},
        {"name": "Mundakakanni AmmanKoil", "code": "MKAK", "category": "SG3", "div": "TPJ", "lat": 10.945, "lng": 79.0121},
        {"name": "Nandiyambakkam (HALT", "code": "NPKM", "category": "SG3", "div": "MAS", "lat": 9.7017, "lng": 79.0498},
        {"name": "Nemilicherry (HALT", "code": "NEC", "category": "SG3", "div": "TPJ", "lat": 8.9173, "lng": 77.2681},
        {"name": "Nungambakkam (FLAG", "code": "NBK", "category": "SG3", "div": "MAS", "lat": 12.5106, "lng": 77.7723},
        {"name": "Pallavaram", "code": "PV", "category": "SG3", "div": "TPJ", "lat": 8.3623, "lng": 77.0468},
        {"name": "Park town (FLAG", "code": "MPKT", "category": "SG3", "div": "MAS", "lat": 12.9929, "lng": 79.6169},
        {"name": "Pattabiram (FLAG", "code": "PAB", "category": "SG3", "div": "TPJ", "lat": 10.9125, "lng": 76.5455},
        {"name": "Pattabiram E-Depot", "code": "PRES", "category": "SG3", "div": "MAS", "lat": 10.7951, "lng": 78.9893},
        {"name": "Pattabiram military siding (FLAG", "code": "PTMS", "category": "SG3", "div": "TPJ", "lat": 10.4284, "lng": 77.5404},
        {"name": "Pattravakkam (FLAG", "code": "PVM", "category": "SG3", "div": "MAS", "lat": 8.0578, "lng": 79.9026},
        {"name": "Perambur carriage works (FLAG", "code": "PCW", "category": "SG3", "div": "TPJ", "lat": 8.2242, "lng": 77.1314},
        {"name": "Perambur loco works (FLAG", "code": "PEW", "category": "SG3", "div": "MAS", "lat": 8.585, "lng": 78.1488},
        {"name": "Perungudi", "code": "PRGD", "category": "SG3", "div": "TPJ", "lat": 8.0631, "lng": 77.4323},
        {"name": "Ponneri", "code": "PON", "category": "SG3", "div": "MAS", "lat": 10.313, "lng": 78.8972},
        {"name": "Puliamanagalam (HALT", "code": "PLMG", "category": "SG3", "div": "TPJ", "lat": 8.6319, "lng": 76.6573},
        {"name": "Putlur (HALT", "code": "PTLR", "category": "SG3", "div": "MAS", "lat": 9.2208, "lng": 76.5038},
        {"name": "Royapuram (HALT", "code": "RPM", "category": "SG3", "div": "TPJ", "lat": 10.9563, "lng": 79.7385},
        {"name": "Saidapet", "code": "SP", "category": "SG3", "div": "MAS", "lat": 10.706, "lng": 79.2785},
        {"name": "Senjipanampakkam (HALT", "code": "SPAM", "category": "SG3", "div": "TPJ", "lat": 11.3922, "lng": 76.1244},
        {"name": "Sevwvapet road", "code": "SVR", "category": "SG3", "div": "MAS", "lat": 12.67, "lng": 76.4364},
        {"name": "St.thomasmount", "code": "STM", "category": "SG3", "div": "TPJ", "lat": 9.4686, "lng": 78.2046},
        {"name": "Tambaram sanitorium (FLAG", "code": "TBMS", "category": "SG3", "div": "MAS", "lat": 8.712, "lng": 79.7629},
        {"name": "Taramani", "code": "TRMN", "category": "SG3", "div": "TPJ", "lat": 9.3673, "lng": 78.7284},
        {"name": "Thirumullaivoil (HALT", "code": "TMVL", "category": "SG3", "div": "MAS", "lat": 8.753, "lng": 78.0347},
        {"name": "Thiruninravur", "code": "Tl", "category": "SG3", "div": "TPJ", "lat": 10.1211, "lng": 79.1144},
        {"name": "Tirumayilai", "code": "MTMY", "category": "SG3", "div": "MAS", "lat": 11.2402, "lng": 77.1239},
        {"name": "Tirusulam (FLAG", "code": "TLM", "category": "SG3", "div": "TPJ", "lat": 11.2561, "lng": 76.5028},
        {"name": "Tiruvalangadu", "code": "TO", "category": "SG3", "div": "MAS", "lat": 8.5916, "lng": 76.268},
        {"name": "Tiruvallikeni (FLAG", "code": "MTCN", "category": "SG3", "div": "TPJ", "lat": 9.0704, "lng": 76.7035},
        {"name": "Tiruvanmiyur", "code": "TYMR:", "category": "SG3", "div": "MAS", "lat": 11.5186, "lng": 76.6371},
        {"name": "Tiruvottiyur", "code": "TVT", "category": "SG3", "div": "TPJ", "lat": 10.1824, "lng": 78.8411},
        {"name": "Tondiarpet (FLAG", "code": "TNP", "category": "SG3", "div": "MAS", "lat": 12.7582, "lng": 77.6292},
        {"name": "", "code": "Veppambattu (FLAG)", "category": "VEU", "div": "TPJ", "lat": 9.1085, "lng": 77.2648},
        {"name": "Villivakkam", "code": "VLK", "category": "SG3", "div": "MAS", "lat": 10.9439, "lng": 79.6711},
        {"name": "Voc nagar", "code": "VOC", "category": "SG3", "div": "TPJ", "lat": 12.7697, "lng": 76.3584},
        {"name": "", "code": "Vyasarpadi jeeva (FLAG)", "category": "VJM", "div": "MAS", "lat": 9.3102, "lng": 77.9738},
        {"name": "Washermanpet", "code": "WST", "category": "SG3", "div": "TPJ", "lat": 12.2526, "lng": 77.583},
        {"name": "Wimco nagar (FLAG", "code": "WCN", "category": "SG3", "div": "MAS", "lat": 10.5216, "lng": 77.7732},
        {"name": "", "code": "Anavardikanpettai (HALT)", "category": "AVN", "div": "TPJ", "lat": 10.4491, "lng": 77.2471},
        {"name": "Kanchipuram east (HALT", "code": "CJE", "category": "HG 1", "div": "MAS", "lat": 10.449, "lng": 76.7617},
        {"name": "Maraimalai nagar (HALT", "code": "MMNK", "category": "HG 1", "div": "TPJ", "lat": 9.0559, "lng": 78.356},
        {"name": "Paranur (HALT", "code": "PWU", "category": "HG 1", "div": "MAS", "lat": 10.6248, "lng": 78.3184},
        {"name": "Potheri (HALT", "code": "POT!", "category": "HG 1", "div": "TPJ", "lat": 11.8225, "lng": 79.0457},
        {"name": "Urappakkam (HALT", "code": "UPM", "category": "HG 1", "div": "MAS", "lat": 8.6608, "lng": 77.7851},
        {"name": "Melattur (HALT", "code": "MLTR", "category": "HG 1", "div": "TPJ", "lat": 12.2524, "lng": 77.4677},
        {"name": "Pattikkad (HALT", "code": "PKQ", "category": "HG 1", "div": "MAS", "lat": 9.9606, "lng": 77.9217},
        {"name": "Divine nagar (HALT", "code": "DINR", "category": "HG 1", "div": "TPJ", "lat": 12.5963, "lng": 77.3802},
        {"name": "Koratti angadi (HALT", "code": "KRAN", "category": "HG 1", "div": "MAS", "lat": 9.3, "lng": 78.4598},
        {"name": "Villiyanur (HALT", "code": "vi", "category": "HG 1", "div": "TPJ", "lat": 11.4039, "lng": 77.2725},
        {"name": "Acharapakkam (HALT", "code": "ACK", "category": "HG 2", "div": "MAS", "lat": 9.1417, "lng": 79.2398},
        {"name": "", "code": "Akkampet (HALT)", "category": "AKAT", "div": "TPJ", "lat": 9.3272, "lng": 79.8293},
        {"name": "Melalathur (HALT", "code": "MEH", "category": "HG 2", "div": "MAS", "lat": 11.9496, "lng": 76.9053},
        {"name": "Villiambakkam (HALT", "code": "VB", "category": "HG 2", "div": "TPJ", "lat": 8.0159, "lng": 77.5511},
        {"name": "Virinchipuram (HALT", "code": "Vd", "category": "HG 2", "div": "MAS", "lat": 10.3779, "lng": 79.1322},
        {"name": "", "code": "Ayodhyapattanam (HALT)", "category": "APN", "div": "TPJ", "lat": 9.1531, "lng": 78.7173},
        {"name": "Irugur (HALT", "code": "IGU", "category": "HG 2", "div": "MAS", "lat": 10.0326, "lng": 78.7177},
        {"name": "Kuttakudi (HALT", "code": "KKTI", "category": "HG 2", "div": "TPJ", "lat": 9.5751, "lng": 78.637},
        {"name": "Melnariyappanur (HALT", "code": "MLYR", "category": "HG 2", "div": "MAS", "lat": 11.4148, "lng": 76.9892},
        {"name": "Periyanaikanpalaiyam (HALT", "code": "PKM", "category": "HG 2", "div": "TPJ", "lat": 11.5871, "lng": 78.2623},
        {"name": "Singanallur (HALT", "code": "SHI", "category": "HG 2", "div": "MAS", "lat": 8.4821, "lng": 77.231},
        {"name": "Siruvattur (HALT", "code": "SRVT", "category": "HG 2", "div": "TPJ", "lat": 9.719, "lng": 77.0886},
        {"name": "Talaivasal (HALT", "code": "Tvs", "category": "HG 2", "div": "MAS", "lat": 8.1425, "lng": 78.5983},
        {"name": "Thonganur (HALT", "code": "TNGR", "category": "HG 2", "div": "TPJ", "lat": 9.9852, "lng": 76.6707},
        {"name": "Vallapadi gate (HALT", "code": "VGE", "category": "HG 2", "div": "MAS", "lat": 11.5882, "lng": 79.906},
        {"name": "Chandera (HALT", "code": "CDRA", "category": "HG 2", "div": "TPJ", "lat": 8.926, "lng": 77.2179},
        {"name": "Chemancheri (HALT", "code": "CMC", "category": "HG 2", "div": "MAS", "lat": 11.0275, "lng": 78.414},
        {"name": "Cherukara (HALT", "code": "CQA", "category": "HG 2", "div": "TPJ", "lat": 8.4307, "lng": 78.6786},
        {"name": "Elimala (Halt", "code": "ELM", "category": "HG 2", "div": "MAS", "lat": 10.34, "lng": 76.3471},
        {"name": "Jagannath temple gate (Halt", "code": "JGE", "category": "HG 2", "div": "TPJ", "lat": 8.4755, "lng": 76.299},
        {"name": "Kalanad (HALT", "code": "KLAD", "category": "HG 2", "div": "MAS", "lat": 12.8741, "lng": 78.1367},
        {"name": "Kulukkallur (HALT", "code": "KZC", "category": "HG 2", "div": "TPJ", "lat": 12.311, "lng": 77.2927},
        {"name": "Mukkali (HALT", "code": "MUKE", "category": "HG 2", "div": "MAS", "lat": 10.809, "lng": 78.0208},
        {"name": "Nadapuram road (HALT", "code": "NAU", "category": "HG 2", "div": "TPJ", "lat": 8.0207, "lng": 78.3614},
        {"name": "Pappinisseri (Halt", "code": "PPNS", "category": "HG 2", "div": "MAS", "lat": 8.9327, "lng": 79.1607},
        {"name": "Todiyappulam (HALT", "code": "TDPM", "category": "HG 2", "div": "TPJ", "lat": 12.6462, "lng": 78.2547},
        {"name": "Tuvvur (HALT", "code": "TUV", "category": "HG 2", "div": "MAS", "lat": 12.9, "lng": 76.3719},
        {"name": "", "code": "Vadanamkurushshi (HALT)", "category": "VDKS", "div": "TPJ", "lat": 9.7549, "lng": 79.5013},
        {"name": "Vallapuzha (HALT", "code": "VPZ", "category": "HG 2", "div": "MAS", "lat": 8.7796, "lng": 77.0567},
        {"name": "Vellayil (HALT", "code": "VLL", "category": "HG 2", "div": "TPJ", "lat": 12.6843, "lng": 77.4423},
        {"name": "", "code": "Amaravila (HALT)", "category": "AMVA", "div": "MAS", "lat": 10.8727, "lng": 77.5325},
        {"name": "Balaramapuram (Halt", "code": "BRAM", "category": "HG 2", "div": "TPJ", "lat": 11.0313, "lng": 76.8334},
        {"name": "Cheriyanad (HALT", "code": "CYN", "category": "HG 2", "div": "MAS", "lat": 11.3456, "lng": 76.4664},
        {"name": "Chowvara (HALT", "code": "CWR", "category": "HG 2", "div": "TPJ", "lat": 8.4068, "lng": 76.2182},
        {"name": "Dhanuvachapuram (HALT", "code": "DAVM", "category": "HG 2", "div": "MAS", "lat": 12.124, "lng": 77.4689},
        {"name": "lravipuram (HALT", "code": "IRP", "category": "HG 2", "div": "TPJ", "lat": 8.4509, "lng": 79.9444},
        {"name": "Kalavur (HALT", "code": "KAVR", "category": "HG 2", "div": "MAS", "lat": 12.6378, "lng": 78.1519},
        {"name": "Kanjiramittam (HALT", "code": "KPTM", "category": "HG 2", "div": "TPJ", "lat": 9.6103, "lng": 77.1794},
        {"name": "Karuvatta (HALT", "code": "KVTA", "category": "HG 2", "div": "MAS", "lat": 9.8276, "lng": 78.7503},
        {"name": "Kulitturai west (HALT", "code": "KZTW", "category": "HG 2", "div": "TPJ", "lat": 11.6986, "lng": 77.574},
        {"name": "Mullurcarai (HALT", "code": "MUC", "category": "HG 2", "div": "MAS", "lat": 10.2602, "lng": 78.7291},
        {"name": "Munroturuttu (HALT", "code": "MQO,", "category": "HG 2", "div": "TPJ", "lat": 11.6758, "lng": 78.0632},
        {"name": "Nellayi (HALT", "code": "NYI", "category": "HG 2", "div": "MAS", "lat": 12.8983, "lng": 79.9229},
        {"name": "Palliyadi (HALT", "code": "PYD", "category": "HG 2", "div": "TPJ", "lat": 11.0547, "lng": 79.5913},
        {"name": "Perunguzhi (HALT", "code": "PGZ", "category": "HG 2", "div": "MAS", "lat": 10.7657, "lng": 77.5692},
        {"name": "Punnapra (HALT", "code": "PNPR", "category": "HG 2", "div": "TPJ", "lat": 9.7078, "lng": 76.0237},
        {"name": "Tumboli (HALT", "code": "TMPY", "category": "HG 2", "div": "MAS", "lat": 10.727, "lng": 78.7296},
        {"name": "", "code": "\Vayalar (HALT)", "category": "VAY", "div": "TPJ", "lat": 11.6258, "lng": 79.9355},
        {"name": "Veli (HALT", "code": "VELI", "category": "HG 2", "div": "MAS", "lat": 11.0547, "lng": 78.4521},
        {"name": "Virani alur (HALT", "code": "VRLR", "category": "HG 2", "div": "TPJ", "lat": 10.6398, "lng": 79.0597},
        {"name": "", "code": "Aiyanapuram (HALT)", "category": "AYN", "div": "MAS", "lat": 10.6175, "lng": 77.6299},
        {"name": "", "code": "Ammapet (HALT)", "category": "AMT", "div": "TPJ", "lat": 9.6348, "lng": 78.6172},
        {"name": "Darasuram (HALT", "code": "DSM", "category": "HG 2", "div": "MAS", "lat": 8.4244, "lng": 79.2046},
        {"name": "Manjattidal (HALT", "code": "MCJ", "category": "HG 2", "div": "TPJ", "lat": 12.34, "lng": 76.8195},
        {"name": "Nidur (HALT", "code": "NID", "category": "HG 2", "div": "MAS", "lat": 12.6163, "lng": 76.6857},
        {"name": "Parangipettai (HALT", "code": "PO", "category": "HG 2", "div": "TPJ", "lat": 9.3599, "lng": 78.0199},
        {"name": "Pichchandar Koil (HALT", "code": "BxXS.", "category": "HG 2", "div": "MAS", "lat": 10.4783, "lng": 79.5474},
        {"name": "Swamimalai (HALT", "code": "SWI", "category": "HG 2", "div": "TPJ", "lat": 10.7519, "lng": 77.8589},
        {"name": "Tiruchchirappalli palakarai (HALT", "code": "TPE", "category": "HG 2", "div": "MAS", "lat": 12.1945, "lng": 78.4641},
        {"name": "Tiruvidaimarudur (HALT", "code": "TDR", "category": "HG 2", "div": "TPJ", "lat": 12.1886, "lng": 78.0735},
        {"name": "\Valavanur (HALT", "code": "VRA", "category": "HG 2", "div": "MAS", "lat": 12.4429, "lng": 77.9915},
        {"name": "Velippalaiyam (HALT", "code": "VXM", "category": "HG 2", "div": "TPJ", "lat": 10.5849, "lng": 77.5117},
        {"name": "Velore town (HALT", "code": "VT", "category": "HG 2", "div": "MAS", "lat": 11.8537, "lng": 77.7345},
        {"name": "\Vriddhachalam town (HALT", "code": "VRT", "category": "HG 2", "div": "TPJ", "lat": 10.6683, "lng": 76.6577},
        {"name": "Azhwarkurichi (HALT", "code": "AZK", "category": "HG 2", "div": "MAS", "lat": 12.6033, "lng": 76.2545},
        {"name": "Chettiyapatti (HALT", "code": "cil", "category": "HG 2", "div": "TPJ", "lat": 11.4143, "lng": 78.6461},
        {"name": "Kailasapuram (HALT", "code": "KLPM", "category": "HG 2", "div": "MAS", "lat": 10.7262, "lng": 76.8207},
        {"name": "Karaikkurichchi (HALT", "code": "KARK", "category": "HG 2", "div": "TPJ", "lat": 11.6142, "lng": 79.4508},
        {"name": "Kizha ambur (HALT", "code": "KIB", "category": "HG 2", "div": "MAS", "lat": 11.275, "lng": 78.0619},
        {"name": "Kottaiyur (HALT", "code": "KTYR", "category": "HG 2", "div": "TPJ", "lat": 11.3348, "lng": 79.388},
        {"name": "Kuri (HALT", "code": "KIF", "category": "HG 2", "div": "MAS", "lat": 11.1423, "lng": 77.9428},
        {"name": "Madathukulam (HALT", "code": "MDKM", "category": "HG 2", "div": "TPJ", "lat": 8.5142, "lng": 79.9766},
        {"name": "Mandapam camp (HALT", "code": "MC.", "category": "HG 2", "div": "MAS", "lat": 8.1177, "lng": 78.4684},
        {"name": "Naraikkinar (Halt", "code": "NRK", "category": "HG 2", "div": "TPJ", "lat": 11.8058, "lng": 78.9819},
        {"name": "Tutimelur (HALT", "code": "TME", "category": "HG 2", "div": "MAS", "lat": 9.6801, "lng": 78.2633},
        {"name": "Valantaravai (HALT", "code": "VIV", "category": "HG 2", "div": "TPJ", "lat": 9.5988, "lng": 78.4794},
        {"name": "Viravanallur (HALT", "code": "VVR", "category": "HG 2", "div": "MAS", "lat": 9.7934, "lng": 77.456},
        {"name": "Ichchiputtur (HALT", "code": "IPT", "category": "HG 3", "div": "TPJ", "lat": 8.5657, "lng": 76.1634},
        {"name": "Nathapettai (HALT", "code": "NTT", "category": "HG 3", "div": "MAS", "lat": 12.9083, "lng": 76.6995},
        {"name": "Padalam (HALT", "code": "PTM", "category": "HG 3", "div": "TPJ", "lat": 10.3044, "lng": 76.6367},
        {"name": "Padi (HALT", "code": "PADI", "category": "HG 3", "div": "MAS", "lat": 10.2997, "lng": 78.6994},
        {"name": "Palayasivaram (HALT", "code": "PYV", "category": "HG 3", "div": "TPJ", "lat": 12.4086, "lng": 77.5873},
        {"name": "Reddipalayam (HALT", "code": "RDY", "category": "HG 3", "div": "MAS", "lat": 12.5788, "lng": 77.5268},
        {"name": "Thakkolam (HALT", "code": "TKO", "category": "HG 3", "div": "TPJ", "lat": 10.3085, "lng": 76.7361},
        {"name": "/\Venkatanarasimharajuvaripeta (HALT", "code": "VKZ", "category": "HG 3", "div": "MAS", "lat": 9.4127, "lng": 76.0902},
        {"name": "Jiyapuram (HALT", "code": "JPM", "category": "HG 3", "div": "TPJ", "lat": 9.2566, "lng": 76.7485},
        {"name": "Kunnattur (HALT", "code": "KNNT", "category": "HG 3", "div": "MAS", "lat": 10.5541, "lng": 77.1247},
        {"name": "Marudur (HALT", "code": "MUQ", "category": "HG 3", "div": "TPJ", "lat": 11.0528, "lng": 77.0286},
        {"name": "Thudiyalur (HALT", "code": "TDE", "category": "HG 3", "div": "MAS", "lat": 12.3128, "lng": 76.5952},
        {"name": "Timmachipuram (HALT", "code": "TIC", "category": "HG 3", "div": "TPJ", "lat": 12.0637, "lng": 78.1382},
        {"name": "Vangal (HALT", "code": "VNGL", "category": "HG 3", "div": "MAS", "lat": 9.8867, "lng": 79.5311},
        {"name": "Anamalai road (HALT", "code": "ANM", "category": "HG 3", "div": "TPJ", "lat": 11.7883, "lng": 76.0389},
        {"name": "Chirakkal (HALT", "code": "cal", "category": "HG 3", "div": "MAS", "lat": 10.9403, "lng": 77.485},
        {"name": "Dharmadam (HALT", "code": "DMD", "category": "HG 3", "div": "TPJ", "lat": 9.4359, "lng": 76.8124},
        {"name": "Iringal (HALT", "code": "IGL", "category": "HG 3", "div": "MAS", "lat": 9.1407, "lng": 78.7476},
        {"name": "Kodumunda (HALT", "code": "KODN", "category": "HG 3", "div": "TPJ", "lat": 11.0731, "lng": 78.2979},
        {"name": "Mankara (HALT", "code": "MNY", "category": "HG 3", "div": "MAS", "lat": 12.6546, "lng": 79.3672},
        {"name": "Palappuram (HALT", "code": "PLPM", "category": "HG 3", "div": "TPJ", "lat": 10.0298, "lng": 76.0654},
        {"name": "Perashshannur (HALT", "code": "PEU", "category": "HG 3", "div": "MAS", "lat": 12.9277, "lng": 77.2383},
        {"name": "\Vadakannikapuram (HALT", "code": "VDK", "category": "HG 3", "div": "TPJ", "lat": 9.5822, "lng": 78.3535},
        {"name": "Vellarakkad (HALT", "code": "VEK", "category": "HG 3", "div": "MAS", "lat": 11.977, "lng": 79.3151},
        {"name": "Akathumuri (HALT", "code": "AMY", "category": "HG 3", "div": "TPJ", "lat": 9.005, "lng": 79.9708},
        {"name": "Aroor (HALT", "code": "AROR", "category": "HG 3", "div": "MAS", "lat": 9.7766, "lng": 76.3484},
        {"name": "Chottanikara road (HALT", "code": "KFE", "category": "HG 3", "div": "TPJ", "lat": 10.0097, "lng": 78.4049},
        {"name": "Ezhupunna (HALT", "code": "EZP", "category": "HG 3", "div": "MAS", "lat": 11.2136, "lng": 76.9566},
        {"name": "Kaduturutty (HALT", "code": "KDTY", "category": "HG 3", "div": "TPJ", "lat": 10.9571, "lng": 76.4558},
        {"name": "Kappil (HALT", "code": "KFI", "category": "HG 3", "div": "MAS", "lat": 12.4515, "lng": 76.799},
        {"name": "Kavalkinaru (HALT", "code": "KVLK", "category": "HG 3", "div": "TPJ", "lat": 8.6593, "lng": 78.3108},
        {"name": "Kumaranallur (HALT", "code": "KFQ", "category": "HG 3", "div": "MAS", "lat": 10.7968, "lng": 77.2996},
        {"name": "Melappalayam (HALT", "code": "MP.", "category": "HG 3", "div": "TPJ", "lat": 8.8277, "lng": 76.9164},
        {"name": "Takazhi (HALT", "code": "TZH", "category": "HG 3", "div": "MAS", "lat": 11.4711, "lng": 76.3687},
        {"name": "Tiruvizha (HALT", "code": "TRVZ", "category": "HG 3", "div": "TPJ", "lat": 9.6238, "lng": 79.3173},
        {"name": "Tovalai (HALT", "code": "THX", "category": "HG 3", "div": "MAS", "lat": 12.0208, "lng": 76.7425},
        {"name": "Adhichchanur (HALT", "code": "ACN", "category": "HG 3", "div": "TPJ", "lat": 9.2153, "lng": 78.5669},
        {"name": "", "code": "Adiyakkamangalam (HALT)", "category": "AYM", "div": "MAS", "lat": 12.3619, "lng": 78.5657},
        {"name": "", "code": "Alattambadi (HALT)", "category": "ATB", "div": "TPJ", "lat": 10.5715, "lng": 77.5227},
        {"name": "", "code": "Ammanur (HALT)", "category": "AMNR", "div": "MAS", "lat": 10.2096, "lng": 77.8514},
        {"name": "", "code": "Andampallam (HALT)", "category": "AND", "div": "TPJ", "lat": 12.417, "lng": 78.178},
        {"name": "Andanappettai (HALT", "code": "APE", "category": "HG 3", "div": "MAS", "lat": 11.5744, "lng": 79.6155},
        {"name": "Ayandur (HALT", "code": "AYD", "category": "HG 3", "div": "TPJ", "lat": 11.1871, "lng": 76.8103},
        {"name": "", "code": "Ayyampet (HALT)", "category": "AZP", "div": "MAS", "lat": 11.5238, "lng": 76.5513},
        {"name": "Capper quarry (HALT", "code": "cas", "category": "HG 3", "div": "TPJ", "lat": 10.6779, "lng": 77.0223},
        {"name": "Ichchangadu (HALT", "code": "ICGH", "category": "HG 3", "div": "MAS", "lat": 8.9054, "lng": 77.8646},
        {"name": "Kandanur puduvayal (HALT", "code": "KNPL.", "category": "HG 3", "div": "TPJ", "lat": 10.4776, "lng": 77.9644},
        {"name": "Kattur (HALT", "code": "KTTR", "category": "HG 3", "div": "MAS", "lat": 12.5021, "lng": 79.0711},
        {"name": "Koyilvenni (HALT", "code": "KYV", "category": "HG 3", "div": "TPJ", "lat": 10.6408, "lng": 78.9101},
        {"name": "Kudikadu (HALT", "code": "KXO", "category": "HG 3", "div": "MAS", "lat": 8.1929, "lng": 77.8247},
        {"name": "Kuthur (HALT", "code": "KOQ", "category": "HG 3", "div": "TPJ", "lat": 8.9851, "lng": 76.9876},
        {"name": "Madimangalam (HALT", "code": "MCL", "category": "HG 3", "div": "MAS", "lat": 8.9547, "lng": 76.2528},
        {"name": "Manali (HALT", "code": "MNLI", "category": "HG 3", "div": "TPJ", "lat": 11.1814, "lng": 78.7801},
        {"name": "Mangudi (HALT", "code": "MAX", "category": "HG 3", "div": "MAS", "lat": 10.3601, "lng": 79.6507},
        {"name": "Mavur road (HALT", "code": "MARD.", "category": "HG 3", "div": "TPJ", "lat": 11.079, "lng": 78.3666},
        {"name": "Muthupettai (HALT", "code": "MTT", "category": "HG 3", "div": "MAS", "lat": 12.3116, "lng": 78.8017},
        {"name": "Narasinganpet (HALT", "code": "NPT", "category": "HG 3", "div": "TPJ", "lat": 11.1888, "lng": 78.4552},
        {"name": "Onnupuram (HALT", "code": "OPM", "category": "HG 3", "div": "MAS", "lat": 11.2072, "lng": 76.8823},
        {"name": "Ottankadu (HALT", "code": "TCT", "category": "HG 3", "div": "TPJ", "lat": 9.8069, "lng": 78.7197},
        {"name": "Pasupathikoil (HALT", "code": "PVL", "category": "HG 3", "div": "MAS", "lat": 8.8446, "lng": 76.3873},
        {"name": "Pennathur (HALT", "code": "PNTR", "category": "HG 3", "div": "TPJ", "lat": 8.0392, "lng": 79.2283},
        {"name": "Punthottam Halt", "code": "POM", "category": "HG 3", "div": "MAS", "lat": 10.3776, "lng": 76.5513},
        {"name": "Sedarampattu (HALT", "code": "SDPT", "category": "HG 3", "div": "TPJ", "lat": 8.626, "lng": 77.2069},
        {"name": "Sikkal (HALT", "code": "SKK", "category": "HG 3", "div": "MAS", "lat": 10.2429, "lng": 76.7612},
        {"name": "Tirumalairayan Pattinam (HALT", "code": "TMPT", "category": "HG 3", "div": "TPJ", "lat": 10.0484, "lng": 77.1875},
        {"name": "Tirumathikunnam (HALT", "code": "TMU", "category": "HG 3", "div": "MAS", "lat": 9.2169, "lng": 76.0928},
        {"name": "Tirunageswaram (HALT", "code": "TRM", "category": "HG 3", "div": "TPJ", "lat": 11.1426, "lng": 78.8579},
        {"name": "Tondamanpatti (HALT", "code": "TOM", "category": "HG 3", "div": "MAS", "lat": 12.6357, "lng": 77.9292},
        {"name": "Uthamar kovil (HALT", "code": "UKV", "category": "HG 3", "div": "TPJ", "lat": 8.1546, "lng": 76.3739},
        {"name": "Valaramanikkam (HALT", "code": "VMM", "category": "HG 3", "div": "MAS", "lat": 11.8644, "lng": 78.9705},
        {"name": "Vallampadugai (HALT", "code": "VMP", "category": "HG 3", "div": "TPJ", "lat": 12.3472, "lng": 79.8891},
        {"name": "\Varakalpattu (HALT", "code": "VKP", "category": "HG 3", "div": "MAS", "lat": 8.2774, "lng": 76.7569},
        {"name": "Vellur (HALT", "code": "VER", "category": "HG 3", "div": "TPJ", "lat": 12.4716, "lng": 78.9589},
        {"name": "Aryankavu (HALT", "code": "AYV", "category": "HG 3", "div": "MAS", "lat": 9.3132, "lng": 79.8328},
        {"name": "Chandanattop (HALT", "code": "CTPE", "category": "HG 3", "div": "TPJ", "lat": 10.0401, "lng": 79.4718},
        {"name": "Edapalayam (HALT", "code": "EDP", "category": "HG 3", "div": "MAS", "lat": 11.3531, "lng": 78.0047},
        {"name": "Kalthurithi (HALT", "code": "KTHY", "category": "HG 3", "div": "TPJ", "lat": 8.5604, "lng": 77.8426},
        {"name": "Kundara east (HALT", "code": "KFV", "category": "HG 3", "div": "MAS", "lat": 10.3499, "lng": 76.6119},
        {"name": "Nagamalai west (HALT", "code": "NGMW", "category": "HG 3", "div": "TPJ", "lat": 10.2534, "lng": 79.9799},
        {"name": "Namanasamudram (HALT", "code": "NMN", "category": "HG 3", "div": "MAS", "lat": 12.9829, "lng": 78.4745},
        {"name": "Ottakkal (Halt", "code": "OKL", "category": "HG 3", "div": "TPJ", "lat": 10.214, "lng": 79.411},
        {"name": "Rajagambiram (HALT", "code": "RAGM", "category": "HG 3", "div": "MAS", "lat": 12.0652, "lng": 78.1411},
        {"name": "Samudram (HALT", "code": "SMDM", "category": "HG 3", "div": "TPJ", "lat": 9.067, "lng": 78.3059},
        {"name": "\Vadpalanji (HALT", "code": "VAJ", "category": "HG 3", "div": "MAS", "lat": 9.0159, "lng": 77.3389},
    ]
    stations = {}
    for s in station_data:
        existing = db.query(Station).filter(Station.code == s["code"]).first()
        if not existing:
            station = Station(
                name=s["name"],
                code=s["code"],
                category=s["category"],
                division_id=divisions[s["div"]].id,
                gps_lat=s["lat"],
                gps_long=s["lng"],
            )
            db.add(station)
            db.commit()
            db.refresh(station)
            stations[s["code"]] = station
            print(f"  âœ“ Station: {s['name']}")
        else:
            stations[s["code"]] = existing

    # â”€â”€ Water Sources â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    now = datetime.utcnow()
    water_source_data = [
        {
            "source_id_code": "MAS-BW-01",
            "station_code": "MAS",
            "source_type": "Borewell",
            "capacity": "50,000 L/day",
            "areas_supplied": "Platform 1-5, Waiting Hall",
            "storage_tank": "Yes - 2 x 25,000 L",
            "treatment_facility": "Chlorination Plant",
            "disinfection_method": "Chlorination",
            "current_status": "COMPLIANT",
            "last_bacteriological_sample_date": now - timedelta(days=10),
            "next_bacteriological_sample_due": now + timedelta(days=20),
            "last_chemical_sample_date": now - timedelta(days=25),
            "next_chemical_sample_due": now + timedelta(days=65),
            "last_disinfection_date": now - timedelta(days=5),
            "next_disinfection_due": now + timedelta(days=25),
        },
        {
            "source_id_code": "MAS-OW-01",
            "station_code": "MAS",
            "source_type": "Open Well",
            "capacity": "20,000 L/day",
            "areas_supplied": "Goods Shed, Loco Workshop",
            "storage_tank": "Yes - 1 x 20,000 L",
            "treatment_facility": "None",
            "disinfection_method": "Bleaching Powder",
            "current_status": "UNSATISFACTORY",
            "last_bacteriological_sample_date": now - timedelta(days=45),
            "next_bacteriological_sample_due": now - timedelta(days=15),
            "last_chemical_sample_date": now - timedelta(days=100),
            "next_chemical_sample_due": now - timedelta(days=10),
            "last_disinfection_date": now - timedelta(days=40),
            "next_disinfection_due": now - timedelta(days=10),
        },
        {
            "source_id_code": "TBM-PL-01",
            "station_code": "TBM",
            "source_type": "Pipeline (CMWSSB)",
            "capacity": "30,000 L/day",
            "areas_supplied": "Platform 1-3, Staff Quarters",
            "storage_tank": "Yes - 1 x 30,000 L",
            "treatment_facility": "None",
            "disinfection_method": "Chlorination",
            "current_status": "COMPLIANT",
            "last_bacteriological_sample_date": now - timedelta(days=5),
            "next_bacteriological_sample_due": now + timedelta(days=25),
            "last_chemical_sample_date": now - timedelta(days=20),
            "next_chemical_sample_due": now + timedelta(days=70),
            "last_disinfection_date": now - timedelta(days=3),
            "next_disinfection_due": now + timedelta(days=27),
        },
        {
            "source_id_code": "TPJ-BW-01",
            "station_code": "TPJ",
            "source_type": "Borewell",
            "capacity": "40,000 L/day",
            "areas_supplied": "All Platforms, Catering Units",
            "storage_tank": "Yes - 2 x 20,000 L",
            "treatment_facility": "UV Treatment",
            "disinfection_method": "Chlorination + UV",
            "current_status": "UNFIT",
            "last_bacteriological_sample_date": now - timedelta(days=3),
            "next_bacteriological_sample_due": now + timedelta(days=27),
            "last_chemical_sample_date": now - timedelta(days=15),
            "next_chemical_sample_due": now + timedelta(days=75),
            "last_disinfection_date": now - timedelta(days=60),
            "next_disinfection_due": now - timedelta(days=30),
        },
    ]

    for ws in water_source_data:
        existing = db.query(WaterSource).filter(
            WaterSource.source_id_code == ws["source_id_code"]
        ).first()
        if not existing:
            station_code = ws.pop("station_code")
            ws["station_id"] = stations[station_code].id
            source = WaterSource(**ws)
            db.add(source)
            db.commit()
            print(f"  âœ“ Water Source: {ws['source_id_code']}")
        else:
            print(f"  â€“ Water Source already exists: {ws['source_id_code']}")

    # â”€â”€ Parameters â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    parameter_data = [
        {"name": "pH", "category": "Chemical", "unit": "pH units"},
        {"name": "Turbidity", "category": "Chemical", "unit": "NTU"},
        {"name": "Total Dissolved Solids", "category": "Chemical", "unit": "mg/L"},
        {"name": "Chloride", "category": "Chemical", "unit": "mg/L"},
        {"name": "Hardness", "category": "Chemical", "unit": "mg/L"},
        {"name": "Total Coliform", "category": "Bacteriological", "unit": "MPN/100mL"},
        {"name": "E. coli", "category": "Bacteriological", "unit": "MPN/100mL"},
        {"name": "Residual Chlorine", "category": "Chemical", "unit": "mg/L"},
        {"name": "Nitrate", "category": "Chemical", "unit": "mg/L"},
        {"name": "Fluoride", "category": "Chemical", "unit": "mg/L"},
    ]
    parameters = {}
    for p in parameter_data:
        existing = db.query(Parameter).filter(Parameter.name == p["name"]).first()
        if not existing:
            param = Parameter(**p)
            db.add(param)
            db.commit()
            db.refresh(param)
            parameters[p["name"]] = param
            print(f"  âœ“ Parameter: {p['name']}")
        else:
            parameters[p["name"]] = existing

    # â”€â”€ Quality Standards (BIS IS 10500) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    standard_data = [
        {"parameter": "pH", "type": "BIS IS 10500", "acceptable": 6.5, "permissible": 8.5},
        {"parameter": "Turbidity", "type": "BIS IS 10500", "acceptable": 1.0, "permissible": 5.0},
        {"parameter": "Total Dissolved Solids", "type": "BIS IS 10500", "acceptable": 500.0, "permissible": 2000.0},
        {"parameter": "Chloride", "type": "BIS IS 10500", "acceptable": 250.0, "permissible": 1000.0},
        {"parameter": "Hardness", "type": "BIS IS 10500", "acceptable": 200.0, "permissible": 600.0},
        {"parameter": "Total Coliform", "type": "BIS IS 10500", "acceptable": 0.0, "permissible": 0.0},
        {"parameter": "E. coli", "type": "BIS IS 10500", "acceptable": 0.0, "permissible": 0.0},
        {"parameter": "Residual Chlorine", "type": "BIS IS 10500", "acceptable": 0.2, "permissible": 1.0},
        {"parameter": "Nitrate", "type": "BIS IS 10500", "acceptable": 45.0, "permissible": 100.0},
        {"parameter": "Fluoride", "type": "BIS IS 10500", "acceptable": 1.0, "permissible": 1.5},
    ]
    for s in standard_data:
        param = parameters.get(s["parameter"])
        if param:
            existing = db.query(WaterQualityStandard).filter(
                WaterQualityStandard.parameter_id == param.id,
                WaterQualityStandard.standard_type == s["type"]
            ).first()
            if not existing:
                std = WaterQualityStandard(
                    parameter_id=param.id,
                    standard_type=s["type"],
                    acceptable_limit=s["acceptable"],
                    permissible_limit=s["permissible"],
                    is_active=True,
                )
                db.add(std)
                db.commit()
                print(f"  âœ“ Standard: {s['parameter']} ({s['type']})")

    print("\nâœ… Seeding complete!")
    print("   Login: employee_id=ADMIN001, password=admin123")

if __name__ == "__main__":
    try:
        seed_all()
    finally:
        db.close()

